### ISSUE TITLE
Exception when try to deploy runtime

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#150]
When I try to deploy new runtime by:
```
./pywren_runtime build omerb01/pywren-omer-runtime:3.6
```
I get:
```
Traceback (most recent call last):
  File "./pywren_runtime", line 5, in <module>
    from pywren_ibm_cloud.runtime.pywren_runtime_cli import cli
ModuleNotFoundError: No module named 'pywren_ibm_cloud.runtime.pywren_runtime_cli'
```

**Comment by JosepSampe** [comment]
@omerb01 How do you have installed the PW package? pip install..? python setup.py develop?

**Comment by omerb01** [comment]
@JosepSampe python setup.py develop

**Comment by JosepSampe** [comment]
@omerb01 I just installed PW in a clean VM with `python3 setup.py develop` and it works fine.
Ensure you have installed latest commit... try re-running `python3 setup.py develop` command again.

**Comment by omerb01** [comment]
@JosepSampe I removed the entire python installation and reinstall it (and pywren) as a fresh clean installation but it still prints the same exception, im not sure why

**Comment by gilv** [comment]
@JosepSampe I have to say that 

Traceback (most recent call last):
  File "./pywren_runtime", line 5, in <module>
    from pywren_ibm_cloud.runtime.pywren_runtime_cli import cli
ModuleNotFoundError: No module named 'pywren_ibm_cloud.runtime.pywren_runtime_cli'

is not informative enough ;) may be we revert to full trace? :)

**Comment by omerb01** [comment]
@JosepSampe I managed to solve this problem of mine by `pip uninstall pywren_ibm_cloud` and use pywren from `python3 setup.py develop`. when I use both, it gets conflicts - FYI if it's ok.

btw, now I get another exception while I try to use the script (for example "clean"):
```
INFO:pywren_ibm_cloud.runtime.deploy_utils:Cleaning runtimes
DEBUG:pywren_ibm_cloud.storage.backends.cos:Set IBM COS Endpoint to https://s3-api.us-geo.objectstorage.softlayer.net
DEBUG:pywren_ibm_cloud.storage.backends.cos:Set IBM IAM Auth Endpoint to https://iam.cloud.ibm.com/oidc/token
DEBUG:pywren_ibm_cloud.storage.backends.cos:IBM COS using access_key and secret_key
DEBUG:pywren_ibm_cloud.libs.ibm_cf.cf_connector:IBM Cloud Functions init for namespace: pywren_dev_us_east
DEBUG:pywren_ibm_cloud.libs.ibm_cf.cf_connector:IBM Cloud Functions init for host: https://us-east.functions.cloud.ibm.com
DEBUG:pywren_ibm_cloud.libs.ibm_cf.cf_connector:CF user agent set to: python-requests/2.22.0 pywren-ibm-cloud/1.0.13
Traceback (most recent call last):
  File "/Users/omerbelh/IdeaProjects/WORK/pywren-ibm-cloud/runtime/pywren_runtime", line 9, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/omerbelh/IdeaProjects/WORK/pywren-ibm-cloud/pywren_ibm_cloud/runtime/pywren_runtime_cli.py", line 42, in clean
    clean_runtimes()
  File "/Users/omerbelh/IdeaProjects/WORK/pywren-ibm-cloud/pywren_ibm_cloud/runtime/deploy_utils.py", line 247, in clean_runtimes
    runtimes = bh.list_keys_with_prefix(storage_config['storage_bucket'], 'runtime')
  File "/Users/omerbelh/IdeaProjects/WORK/pywren-ibm-cloud/pywren_ibm_cloud/storage/backends/cos.py", line 235, in list_keys_with_prefix
    for page in page_iterator:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ibm_botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key ID you provided does not exist in our records.
```
do you know what does it mean? 
thanks.

**Comment by JosepSampe** [comment]
> @JosepSampe I have to say that
> 
> Traceback (most recent call last):
> File "./pywren_runtime", line 5, in 
> from pywren_ibm_cloud.runtime.pywren_runtime_cli import cli
> ModuleNotFoundError: No module named 'pywren_ibm_cloud.runtime.pywren_runtime_cli'
> 
> is not informative enough ;) may be we revert to full trace? :)

@gilv this is not related with what we discussed. Full tracebacks are always showed ;)

**Comment by JosepSampe** [comment]
@omerb01 Seems to be normal that it gets conflicts if you have PyWren (or any other package) installed both by pip and by `setup.py develop`, since each one will get the source code from different locations, and local modifications might not be reflected (as it happened now).

About the error you mentioned, seems that it fails with COS credentials. you are using AccessKey and SecretKey, right? I'm too, and in my case it works. Try generating new HMAC credentials.

**Comment by omerb01** [comment]
@JosepSampe Thanks a lot for the help.
the problem was that my old config file contained:
```
access_key : <ACCESS_KEY>  # Optional
secret_key : <SECRET_KEY>  # Optional
```
