### ISSUE TITLE
readme is not updated

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#154]
https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/dev-installation.md

Stil contains "deploy_runtime", while it should be "PyWren_runtime", etc.

**Comment by gilv** [comment]
@JosepSampe merging your recent code, getting

DEBUG:pywren_ibm_cloud.storage.backends.cos:PUT Object runtimes/1.0.13/us-east/pywren_dev_us_east/cactusone_pywren-dev_3.6.1_256MB.meta.json - Size: 7.0KiB - OK
Traceback (most recent call last):
  File "./pywren_runtime", line 9, in <module>
    sys.exit(cli())
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/pywren_runtime_cli.py", line 25, in build
    build_runtime(image_name)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py", line 156, in build_runtime
    update_runtime(image_name, config=config)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py", line 184, in update_runtime
    action_image_name, memory = unformat_action_name(action['name'])
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/utils.py", line 58, in unformat_action_name
    runtime_name, memory = action_name.rsplit('_', 1)
ValueError: not enough values to unpack (expected 2, got 1)
gilv1-mac:runtime gilv$

**Comment by JosepSampe** [comment]
@gilv Which command did you run?

**Comment by gilv** [comment]
@JosepSampe ./pywren_runtime build cactusone/pywren-dev:3.6.1

**Comment by JosepSampe** [comment]
@gilv hmmm.. It ran ok for me.
I think I already know what is the problem... I had to change the naming of the functions in the CF namespace in order to add support to run `pywren_runtime update all`. So I guess now you have functions with old naming in your CF namespace..

Run `./pywren_runtime clean` ;)

**Comment by gilv** [comment]
@JosepSampe what this ./pywren_runtime clean does? Clean all PyWren runtimes from my account? if so, does everybody require to run it also? like metabolomics?

**Comment by JosepSampe** [comment]
@gilv It deletes all the actions in the account. Yep, metabolomics also has to run it. Note that it happens because this change is in the same revision (1.0.13), if you create a new revision, it won't happen.

**Comment by gilv** [comment]
@JosepSampe if I will release now 1.0.14, then no need to run clean?

**Comment by JosepSampe** [comment]
@gilv Exact
