### ISSUE TITLE
prevent Jupyter from being serialised

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#179]
I have noticed that when I use PyWren over Jupyter notebooks, PyWren detects that it needs to serialise Jupyter module - 14MB in estimate.
is it possible to prevent this part? or maybe we should add Jupyter module to the default runtime.

**Comment by JosepSampe** [comment]
@omerb01 Can you share DEBUG logs of 1 execution?

**Comment by gilv** [comment]
@JosepSampe I observed the same...I think if you have couple of Jupiter cells and run PyWren from another cell - you will notice in DEBUG logs that also Jupyter model is serialised..

**Comment by omerb01** [comment]
@JosepSampe I haven't managed to produce DEBUG logs due to #178 , will do that after we will solve these issues with CF team

**Comment by JosepSampe** [comment]
@omerb01 map(), map_reduce() methods have a special parameter called `exclude_modules`, used to prevent serializing the desired modules. 

Just as an experiment, can you try adding this in the notebook to see what happens?:
`pw.map(..., ..., ..., exclude_modules=['jupyter'] )`

**Comment by gilv** [comment]
@JosepSampe was this always present? I didn't knew those parameters..they not documented anywhere

**Comment by JosepSampe** [comment]
@gilv Yep, this was present from the beginning

**Comment by omerb01** [comment]
@JosepSampe `exclude_modules` parameter doesn't help in that case because `Jupyter` comes with a bunch of modules that all sums up in 14MB.
if I use this feature, PyWren doesn't serialise `Jupyter` but does serialise everything else - 13MB in estimate.
tested it a bit and I think that these are the modules I'm talking about:
```
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pyrsistent',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/entrypoints.py',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ipython_genutils',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ipywidgets',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/backcall',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/prometheus_client',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/colorama',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/wcwidth',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/defusedxml',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyter_client',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ipykernel',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/testpath',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/bleach',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/IPython',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/decorator.py',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pexpect',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/traitlets',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ptyprocess',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nbformat',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/prompt_toolkit',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jedi',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pickleshare.py',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/notebook',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/send2trash',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/parso',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/terminado',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyter_core',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/appnope',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/mistune.py',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/webencodings',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jsonschema',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pygments',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/SocketServer.py',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandocfilters.py',
  '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nbconvert'
```

**Comment by omerb01** [comment]
@JosepSampe just a minor suggestion regarding `exclude_modules` parameter:
in DEBUG mode, PyWren prints all modules that it detects for serialising, but when we use this parameter, obviously there are modules that PyWren won't serialise, so I suggest to print all modules that are serialised instead of both.

for example, I get:
```
2019-08-21 11:49:58,283 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: {'/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/send2trash', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/plotly', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pexpect', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/defusedxml', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/metaspace', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/prompt_toolkit', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/webencodings', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nbformat', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/seaborn', '/Users/omerbelh/IdeaProjects/WORK/pywren-annotation-pipeline/annotation_pipeline', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/retrying.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/_plotly_utils', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/wcwidth', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/testpath', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/notebook', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jedi', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/traitlets', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pylab.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/terminado', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/boto3', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/backcall', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pandocfilters.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/_plotly_future_', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/mistune.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/SocketServer.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyter_client', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/parso', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/elasticsearch_dsl', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/IPython', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/s3transfer', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ipywidgets', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/cycler.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/nbconvert', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/bleach', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ptyprocess', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ipykernel', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/prometheus_client', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/decorator.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jsonschema', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/entrypoints.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pygments', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/colorama', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ipython_genutils', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/chart_studio', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pickleshare.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/appnope', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pyparsing.py', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/jupyter_core', '/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pyrsistent'}
```
but the only module that PyWren serialise is actually: `'/Users/omerbelh/IdeaProjects/WORK/pywren-annotation-pipeline/annotation_pipeline'` because I configured `exclude_modules` for all these modules except `annotation_pipeline`.
so in this case, I would expect to see only `annotation_pipeline` module.

**Comment by omerb01** [comment]
@JosepSampe another related suggestion according to: https://github.com/metaspace2020/pywren-annotation-pipeline/issues/39
in addition to `exclude_modules` parameter, we need also `include_modules` parameter which defines modules for serialising. all other modules that aren't in the list, won't be serialised.

another thing I want to bring for the discussion is a feature to use `exclude_modules` or `include_modules` from PyWren config file, so I don't need to change every map call when I need this feature for a whole project.

**Comment by JosepSampe** [comment]
@omerb01 I my case I'm not able to reproduce the issue, jupyter is never serialized in my notebooks. In your case, is jupyter serialized in https://github.com/pywren/pywren-ibm-cloud/blob/master/examples/hello_world.ipynb ? or can you provide a concrete example?

**Comment by omerb01** [comment]
@JosepSampe Jupiter isn't serialised in the example you gave me, my mistake when I said that it happens in all cases.
In my case, I use pywren inside a module that we work on (metabolomics annotation pipeline project). in that module we have a few Jupiter notebooks inside so when I run pywren, it detects that it has to serialise our module and I think that because of these notebooks inside, Jupiter module are also marked as to be serialised.

**Comment by JosepSampe** [comment]
@omerb01 Not sure if it can solve the issue, but in #193 I updated cloudpickle library (which is the reprensible to detect the modules) from version 0.6.1 to 1.2.1. Maybe with this new version pywren avoids to serialize jupyter modules... In any case it would be nice to test it.

**Comment by JosepSampe** [comment]
@omerb01 @gilv Done in #198 

I added `include_modules` parameter where you can set those modules you want to serialize as @omerb01 suggested. If you explicitly set `include_modules=None`, no one module will be serialized.

Additionally, now you can set both  `include_modules` and `exclude_modules` in configuration, in 'pywren' section.

**Comment by JosepSampe** [comment]
@omerb01 Did you tested it?

**Comment by omerb01** [comment]
@JosepSampe sorry for the late response.
I think something wrong with the current implementation.
before this update, there were many modules which detected as to be serialise, and now I think that it doesn't detect any module at all - for every example I get
`pywren_ibm_cloud.job.serialize: Modules to transmit: None`.

example:
```python
import pywren_ibm_cloud as pywren
from colorama import Fore

def map_function(args):
    return Fore.GREEN + "Hello World"

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map(map_function, '', include_modules=['colorama'])
print(pw.get_result())
```
```
2019-09-24 10:44:38,610 [DEBUG] pywren_ibm_cloud.executor: ServerlessExecutor created with ID: 4c5ac6e3-2c1d
2019-09-24 10:44:38,610 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: Set IBM COS Endpoint to https://s3-api.us-geo.objectstorage.softlayer.net
2019-09-24 10:44:38,610 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: Set IBM IAM Auth Endpoint to https://iam.cloud.ibm.com/oidc/token
2019-09-24 10:44:38,610 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: IBM COS: Using COS api_key - Requesting new token
2019-09-24 10:44:40,845 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: IBM CF init for namespace: pywren_dev_us_east
2019-09-24 10:44:40,845 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: IBM CF init for host: https://us-east.functions.cloud.ibm.com
2019-09-24 10:44:40,846 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: IBM CF user agent set to: python-requests/2.22.0 pywren-ibm-cloud/1.0.17
2019-09-24 10:44:40,846 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf: PyWren v1.0.17 init for IBM Cloud Functions - Namespace: pywren_dev_us_east - Region: us-east
2019-09-24 10:44:40,846 [INFO] pywren_ibm_cloud.runtime.runtime: ExecutorID 4c5ac6e3-2c1d - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB
2019-09-24 10:44:40,846 [DEBUG] pywren_ibm_cloud.storage.internal_storage: Runtime metadata not found in local cache. Retrieving it from storage
2019-09-24 10:44:41,710 [DEBUG] pywren_ibm_cloud.runtime.runtime: ExecutorID 4c5ac6e3-2c1d - Runtime ibmfunctions/action-python-v3.6 with 256MB is not yet installed
2019-09-24 10:44:41,710 [INFO] pywren_ibm_cloud.runtime.deploy_utils: Creating new PyWren runtime based on Docker image ibmfunctions/action-python-v3.6
2019-09-24 10:44:41,710 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: Set IBM COS Endpoint to https://s3-api.us-geo.objectstorage.softlayer.net
2019-09-24 10:44:41,710 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: Set IBM IAM Auth Endpoint to https://iam.cloud.ibm.com/oidc/token
2019-09-24 10:44:41,710 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: IBM COS: Using COS api_key - Reusing token
2019-09-24 10:44:41,717 [DEBUG] pywren_ibm_cloud.runtime.deploy_utils: Creating zip action in /Users/omerbelh/IdeaProjects/WORK/pywren-temp/ibmcf_pywren.zip
2019-09-24 10:44:41,744 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: I am about to create the package pywren_v1.0.17
2019-09-24 10:44:42,376 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: OK --> Created package pywren_v1.0.17
2019-09-24 10:44:42,376 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: I am about to create a new cloud function action: ibmfunctions_action-python-v3.6_192MB
2019-09-24 10:44:42,793 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: OK --> Created action ibmfunctions_action-python-v3.6_192MB
2019-09-24 10:44:42,793 [DEBUG] pywren_ibm_cloud.runtime.deploy_utils: Extracting Python modules list from: ibmfunctions/action-python-v3.6
2019-09-24 10:44:43,838 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: Delete cloud function action: ibmfunctions_action-python-v3.6_192MB
2019-09-24 10:44:44,256 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: I am about to create the package pywren_v1.0.17
2019-09-24 10:44:44,673 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: Package pywren_v1.0.17: resource already exists
2019-09-24 10:44:44,674 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: I am about to create a new cloud function action: ibmfunctions_action-python-v3.6_256MB
2019-09-24 10:44:46,791 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: OK --> Created action ibmfunctions_action-python-v3.6_256MB
2019-09-24 10:44:48,016 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: PUT Object runtimes/1.0.17/ibm_cf/us-east/pywren_dev_us_east/ibmfunctions_action-python-v3.6_256MB.meta.json - Size: 7.0KiB - OK
2019-09-24 10:44:48,020 [DEBUG] pywren_ibm_cloud.storage.internal_storage: Runtime metadata found in local cache
2019-09-24 10:44:48,021 [DEBUG] pywren_ibm_cloud.job.job: ExecutorID 4c5ac6e3-2c1d Serializing function and data
2019-09-24 10:44:48,021 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: None
2019-09-24 10:44:48,022 [INFO] pywren_ibm_cloud.job.job: ExecutorID 4c5ac6e3-2c1d - Uploading function and data
2019-09-24 10:44:48,471 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: PUT Object pywren.jobs/4c5ac6e3-2c1d/6e334ccd/aggdata.pickle - Size: 25.0B - OK
2019-09-24 10:44:48,921 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos: PUT Object pywren.jobs/4c5ac6e3-2c1d/6e334ccd/func.pickle - Size: 828.0B - OK
2019-09-24 10:44:48,922 [INFO] pywren_ibm_cloud.invoker: ExecutorID 4c5ac6e3-2c1d - Starting function invocation: map_function() - Total: 1 activations
2019-09-24 10:44:49,558 [DEBUG] pywren_ibm_cloud.libs.ibm.cloudfunctions_client: ExecutorID 4c5ac6e3-2c1d - Function 00000 invocation done! (0.636s) - Activation ID: 8bdbcc2eb8834e229bcc2eb8835e2283
2019-09-24 10:44:49,559 [INFO] pywren_ibm_cloud.executor: ExecutorID 4c5ac6e3-2c1d - Getting results...
2019-09-24 10:45:18,161 [INFO] pywren_ibm_cloud.executor: ExecutorID 4c5ac6e3-2c1d - There was an exception - Activation ID: 8bdbcc2eb8834e229bcc2eb8835e2283
Traceback (most recent call last):

  File "/action/pywren_ibm_cloud/action/jobrunner.py", line 185, in run
  File "/action/pywren_ibm_cloud/action/jobrunner.py", line 132, in _unpickle_function
ModuleNotFoundError: No module named 'colorama'

2019-09-24 10:45:18,162 [INFO] pywren_ibm_cloud.executor: ExecutorID 4c5ac6e3-2c1d - Cleaning temporary data from ibm_cos://omergar/pywren.jobs/4c5ac6e3-2c1d
```

**Comment by omerb01** [comment]
@JosepSampe My bad,
this works:
```python
import pywren_ibm_cloud as pywren
import colorama

def map_function(args):
    return colorama.Fore.GREEN + "Hello World"

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map(map_function, '', include_modules=['colorama'])
print(pw.get_result())
```
and this doesn't:
```python
import pywren_ibm_cloud as pywren
from colorama import Fore

def map_function(args):
    return Fore.GREEN + "Hello World"

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map(map_function, '', include_modules=['colorama'])
print(pw.get_result())
```
is it possible to solve?

**Comment by JosepSampe** [comment]
@omerb01 Yeap, the correct way to do this is:
```
import pywren_ibm_cloud as pywren
import colorama

def map_function(args):
    return colorama.Fore.GREEN + "Hello World"

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map(map_function, '', include_modules=['colorama'])
print(pw.get_result())
```

We found same behavior with @gilv few weeks ago, I think this is something related to cloudpickle lib and not to PyWren. Seems that cloudpickle only pickles those packages you include with `import` statement. if you import something with `from .... import ....`, you are importing things into global namespace, and then cloudpikcle assumes the method or the class you imported is already included in your package, so cloudpickle doesn't serialize it.

The question is, does this: `from colorama import Fore` ever worked in any pywren version? I don't know right now, I have to tes it ;)

**Comment by omerb01** [comment]
@JosepSampe in case of `colorama` module, it didn't work before.
I made some tests and found something interesting.

lets assume we have an internal file named `omer.py`:
```python
def print_omer(str):
    return str
```
and then we want to run this code:
```python
import pywren_ibm_cloud as pywren
from omer import print_omer

def map_function(args):
    return print_omer('Hello World')

pw = pywren.ibm_cf_executor(log_level='DEBUG')
pw.map(map_function, '')
print(pw.get_result())
```
With PyWren version 1.0.17 we could run this code successfully and with the current version it prints `pywren_ibm_cloud.job.serialize: Modules to transmit: None` and raises:
```
Traceback (most recent call last):
  File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 236, in run
  File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 134, in _unpickle_function
ModuleNotFoundError: No module named 'omer'
```
good to mention that the variation of `import omer` works successfully with both versions.

the point is that metabolomics use case is built as a package and PyWren is operated from inside of it so there are lots of uses like `from annotation_pipeline... import ...` and it is quite messy to change everything to be with the prefix `annotation_pipeline.<file>.<method-name>`

**Comment by omerb01** [comment]
@JosepSampe I am not sure if im right, but I made some another tests and I think that `cloudpickle` module is totally different between 0.6.1 and 1.2.1 since each `CloudPickle` object doesn't contain "modules" field anymore. I saw that `cloudpickle` module does detects objects in forms of `from ... import ...` but this kind of usage will be detected as a function instead of a module.

we have this code here:
https://github.com/pywren/pywren-ibm-cloud/blob/40c351a23a6e83c6f61334829bc2beff4ed94782/pywren_ibm_cloud/job/serialize.py#L66

so maybe we need to adjust PyWren for its changes.
also, I found that PyWren contains related cloudpickle code which I think that it isn't in use - inside `libs` directory.

what do you think?

**Comment by JosepSampe** [comment]
@omerb01 I already changed cloudpickle lib to make it working with 1.2.1 ;) 
Pywren uses cloudpickle module located in libs and not the installed one(if you have it installed with pip)

**Comment by omerb01** [comment]
@JosepSampe do you think it is possible to extract these detected functions? so every variation will work: `import ...` and `from ... import ...`

**Comment by JosepSampe** [comment]
@omerb01 Yeap, I already have it working, even the `from colorama import Fore` that never worked.

**Comment by JosepSampe** [comment]
@omerb01 Fix included in #205

**Comment by JosepSampe** [comment]
@omerb01 It would be possible to provide a simple example of what you are running? I mean, I already have `annotation_pileline` in my IDE, so some test.py that I can include in the project and that it calls some internal function of the `annotation_pileline` and that shows what you are seeing in the logs

**Comment by JosepSampe** [comment]
@omerb01 I already have an example. I put this function into annotation_pipeline/fdr.py:
```python
def my_function(a):
    return a
```
Then I created a test.py file in root of pywren-annotation-pipeline, and imported previous func:
```python
from annotation_pipeline.fdr import my_function
```

Now in serialize i get: 

`2019-09-25 15:48:07,607 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: `{'/usr/local/lib/python3.6/dist-packages/nbconvert', '/usr/local/lib/python3.6/dist-packages/uritemplate', '/usr/local/lib/python3.6/dist-packages/send2trash', '/usr/local/lib/python3.6/dist-packages/cloudpickle', '/usr/local/lib/python3.6/dist-packages/wcwidth', '/usr/local/lib/python3.6/dist-packages/ipython_genutils', '/usr/local/lib/python3.6/dist-packages/entrypoints.py', '/usr/local/lib/python3.6/dist-packages/pyImagingMSpec', '/usr/local/lib/python3.6/dist-packages/pyparsing-2.3.1-py3.6.egg/pyparsing.py', '/usr/local/lib/python3.6/dist-packages/jupyter_client', '/usr/local/lib/python3.6/dist-packages/decorator.py', '/usr/local/lib/python3.6/dist-packages/jedi', '/usr/local/lib/python3.6/dist-packages/webencodings', '/usr/local/lib/python3.6/dist-packages/nbformat', '/usr/local/lib/python3.6/dist-packages/pandocfilters.py', '/usr/local/lib/python3.6/dist-packages/prompt_toolkit', '/usr/local/lib/python3.6/dist-packages/traitlets', '/usr/local/lib/python3.6/dist-packages/notebook', '/usr/local/lib/python3.6/dist-packages/jupyter_core', '/usr/local/lib/python3.6/dist-packages/matplotlib-3.0.3-py3.6-linux-x86_64.egg/mpl_toolkits', '/usr/local/lib/python3.6/dist-packages/pyMSpec', '/usr/local/lib/python3.6/dist-packages/pygments', '/usr/lib/python3/dist-packages/pexpect', '/usr/local/lib/python3.6/dist-packages/ptyprocess', '/usr/local/lib/python3.6/dist-packages/jsonschema', '/usr/local/lib/python3.6/dist-packages/testpath', '/usr/local/lib/python3.6/dist-packages/backcall', '/usr/local/lib/python3.6/dist-packages/bleach', '/usr/local/lib/python3.6/dist-packages/IPython', '/usr/local/lib/python3.6/dist-packages/mistune.py', '/usr/local/lib/python3.6/dist-packages/terminado', '/usr/local/lib/python3.6/dist-packages/parso', '/usr/local/lib/python3.6/dist-packages/cycler-0.10.0-py3.6.egg/cycler.py', '/usr/local/lib/python3.6/dist-packages/pickleshare.py', '/usr/local/lib/python3.6/dist-packages/defusedxml', '/usr/local/lib/python3.6/dist-packages/pyrsistent', '/usr/local/lib/python3.6/dist-packages/colorama', '/home/josep/data/eclipse-workspace/pywren-annotation-pipeline/annotation_pipeline', '/usr/local/lib/python3.6/dist-packages/prometheus_client', '/usr/local/lib/python3.6/dist-packages/ipykernel'}``

is this similar to what you get?

**Comment by omerb01** [comment]
@omerb01 yes, but in my case I get a bit more packages, I think it doesn't matter. While putting `include_modules=['annotation_pipeline']`, I would like to serialise only `annotation_pipeline` package.

**Comment by JosepSampe** [comment]
@ Ok, just wanted to know if I'm going in the right direction to reproduce the issue. I think now I have it fixed, doing final tests.

**Comment by JosepSampe** [comment]
@omerb01 I added the fix, you can try if it works for you

**Comment by omerb01** [comment]
@JosepSampe Thanks
