### ISSUE TITLE
exception when creating new runtime

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#187]
./pywren_runtime create aaa/pywren-metabolomics:3.6.11

DEBUG:pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos:Set IBM COS Endpoint to https://s3-api.us-geo.objectstorage.softlayer.net
DEBUG:pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos:IBM COS: Using COS api_key - Requesting new token
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:IBM CF init for namespace: pywren_dev_us_east
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:IBM CF init for host: https://us-east.functions.cloud.ibm.com
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:IBM CF user agent set to: python-requests/2.22.0 pywren-ibm-cloud/1.0.18-snapshot
INFO:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:PyWren v1.0.18-snapshot init for IBM Cloud Functions - Namespace: pywren_dev_us_east - Region: us_east
INFO:pywren_ibm_cloud.runtime.deploy_utils:Creating runtime: aaa/pywren-metabolomics:3.6.11, memory: 256
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:I am about to create the package pywren_v1.0.18-snapshot
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:Package pywren_v1.0.18-snapshot: resource already exists
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:I am about to create a new cloud function action: aaa_pywren-metabolomics_3.6.11_130MB
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:OK --> Created action aaa_pywren-metabolomics_3.6.11_130MB
DEBUG:pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf:Extracting Python modules list from: aaa/pywren-metabolomics:3.6.11
DEBUG:pywren_ibm_cloud.libs.ibm_cloudfunctions.client:Delete cloud function action: aaa_pywren-metabolomics_3.6.11_130MB
Traceback (most recent call last):
  File "./pywren_runtime", line 9, in <module>
    sys.exit(cli())
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/pywren_runtime_cli.py", line 21, in create
    create_runtime(image_name, memory=memory)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/deploy_utils.py", line 39, in create_runtime
    runtime_meta = internal_compute.generate_runtime_meta(name)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/compute.py", line 112, in generate_runtime_meta
    return self.compute_handler.generate_runtime_meta(runtime_name)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py", line 231, in generate_runtime_meta
    raise Exception(runtime_meta)
Exception: {'error': "Failed to pull container image 'aaa/pywren-metabolomics:3.6.11'."}

**Comment by gilv** [comment]
@JosepSampe need your magic touch here... 
by the way, what is the difference between create and build runtime?

**Comment by JosepSampe** [comment]
@gilv `./pywren_runtime create` **only creates the action** in your CF namespace. The docker image name you provide must already exist in the docker hub, so I guess in this issue the image  'aaa/pywren-metabolomics:3.6.11' doesn't exist in docker hub, is for this the exception you got.

In contrast,  `./pywren_runtime build` builds a new docker image based on the Dockerfile, then it pushes it into the docker hub, and finally it creates the action in the CF namespace.
