### ISSUE TITLE
chunks on CSV file doesn't work

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#191]
I have one large CSV file..

````

def csv_parts(key, data_stream, ibm_cos):
    centr_df = pd.read_csv(data_stream)

def my_reduce_function(results):
    for df in results:
        print("aha")
    return "yes"

chunk_size = 64*1024**2 
futures = pw.map_reduce(csv_parts, iterdata, my_reduce_function, chunk_size = chunk_size)

````

Got

````

Traceback (most recent call last):
  File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 189, in run
  File "/Users/xyz/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pywren_ibm_cloud/job/partitioner.py", line 73, in object_processing_wrapper
    return map_function(**map_func_args)
  File "/Users/xyz/Dev/ibm-pywren-internal/examples/monte-carlo-stocks/OmerPickleError.py", line 19, in csv_parts
    centr_df = pd.read_csv(data_stream)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2059, in read
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 950, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 937, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2132, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 5506, saw 9

````

**Comment by JosepSampe** [comment]
@gilv In fact we never supported all kind of csv files. Currently, pywren partitioner only supports files ended by "\n", they might be csv or simple text files. Other csv files may have multiple "\n" within same line, which would provoke partitioner failure. Is this your case? Could you share one line of your csv file?

**Comment by gilv** [comment]
@JosepSampe I think I have a "normal" csv file

````
27634,74046,0,1174.7637670898043,83.97048803725883
27635,74049,1,1174.7738872580583,76.89042708618916
27636,74176,1,1174.9310118976189,76.8904516607015
27637,74505,3,1174.9578933773987,76.91075342073843
27638,74507,3,1174.9642701630075,35.278304167207395
27639,74524,1,1174.9755529210674,79.05399789492232
27640,75115,3,1175.1606041047685,9.313466182127966
27641,76809,0,1175.171240111206,100.0
27642,74046,1,1175.7670601985878,66.7971296126062
27643,74049,2,1175.7772561967947,29.158030498224285
27644,74176,2,1175.9273230508259,92.96222185585896
27645,74524,2,1175.970164912781,97.34247383939453
27646,74327,0,1175.9860181532058,100.0
27647,76809,1,1176.1746007581455,86.58781590503078
27648,74046,2,1176.7643623879158,100.0
27649,74049,3,1176.7806311113495,7.27304651991821
27650,74176,3,1176.9306979040925,71.46270216734545
27651,74524,3,1176.973539675621,76.92400028497244
27652,74327,1,1176.9893762283195,77.98909092753709
27653,76809,2,1177.177973821665,37.06433059325158
27654,74046,3,1177.767731838131,76.85685894618483
27655,74327,2,1177.992743806424,30.003188535133834
27656,76809,3,1178.1812983679615,10.441910067961118
27657,74327,3,1178.996118098905,7.599781540973597
````

**Comment by JosepSampe** [comment]
@gilv Yep, it looks like normal csv. Can you send me a sample of, for example, 10MB or 20MB?

**Comment by JosepSampe** [comment]
@gilv After reviewing it, this case is something weird. The error message says that what fails is line 5506, this means that all previous lines worked ok, so our partitioner worked ok at the beginning of the file. We need to see what line 5506 contains. Is line 5506 the last line of the chunk? 

Can you try using python engine?:
`centr_df = pd.read_csv(data_stream, header=None, engine="python")`
