### ISSUE TITLE
Runtime auto installation script does not work

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#203]
after using `pywren-runtime clean` and then run simple "Hello World" function:
```python
import pywren_ibm_cloud as pywren

def map_function(args):
    return "Hello World"

pw = pywren.ibm_cf_executor()
pw.map(map_function, '')
print(pw.get_result())
```
I get exceptions:
```
PyWren v1.0.21-SNAPSHOT init for IBM Cloud Functions - Namespace: pywren_dev_us_east - Region: us_east
ExecutorID 24d8-4bf3 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB (Installing...)
Traceback (most recent call last):
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 146, in get_object
    r = self.cos_client.get_object(Bucket=bucket_name, Key=key, **extra_get_args)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ibm_botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/ibm_botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ibm_botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/storage/storage.py", line 194, in get_runtime_meta
    json_str = self.storage_handler.get_object(self.bucket, obj_key)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 154, in get_object
    raise StorageNoSuchKeyError(bucket_name, key)
pywren_ibm_cloud.storage.utils.StorageNoSuchKeyError: No such key /omergar/runtimes/1.0.21-SNAPSHOT/ibm_cf/us_east/pywren_dev_us_east/ibmfunctions_action-python-v3.6_256MB.meta.json found in storage.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/runtime.py", line 28, in select_runtime
    runtime_meta = internal_storage.get_runtime_meta(runtime_key)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/storage/storage.py", line 205, in get_runtime_meta
    raise Exception('The runtime {} is not installed.'.format(obj_key))
Exception: The runtime runtimes/1.0.21-SNAPSHOT/ibm_cf/us_east/pywren_dev_us_east/ibmfunctions_action-python-v3.6_256MB.meta.json is not installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerbelh/IdeaProjects/WORK/pywren-temp/main.py", line 7, in <module>
    pw.map(map_function, '')
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 180, in map
    self.executor_id, map_job_id, runtime_memory)
  File "/Users/omerbelh/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pywren_ibm_cloud/runtime/runtime.py", line 39, in select_runtime
    if config['pywren']['separate_preinstalls_func'] is None or config['pywren']['separate_preinstalls_func']:
KeyError: 'separate_preinstalls_func'

**Comment by JosepSampe** [comment]
@omerb01 Same from my side. fixing it

**Comment by gilv** [comment]
@omerb01 is this only for default runtime? somehow i didn't saw this bug in my flows

**Comment by omerb01** [comment]
@gilv for me, this exception is raised with any runtime

**Comment by JosepSampe** [comment]
@gilv This was added here: https://github.com/pywren/pywren-ibm-cloud/pull/202/files#diff-b5c9057884612c1b3376a9a5b76ce668R39

It is already fixed in #204

**Comment by JosepSampe** [comment]
@gilv Is it already working for you with new changes?

**Comment by JosepSampe** [comment]
@omerb01 Is it already working for you with new changes?

**Comment by omerb01** [comment]
@JosepSampe Yep, thanks
