### ISSUE TITLE
read timeout from COS

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#217]
I experience weird exceptions regarding COS client that im not sure if its PyWren related.
while launching 1000 actions that each one calls for 8 objects in COS, I get read time out exception from PyWren's jobrunner code:
```
2019-10-27 13:49:01,474 [INFO] pywren_ibm_cloud.executor: ExecutorID 0b31-48da | JobID M000 - There was an exception - Activation ID: c6d09489f6844645909489f684f64552
Traceback (most recent call last):
  File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 234, in run
  File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 88, in _get_function_and_modules
  File "/action/pywren_ibm_cloud/storage/storage.py", line 102, in get_func
  File "/action/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 150, in get_object
  File "/usr/local/lib/python3.6/site-packages/ibm_botocore/response.py", line 81, in read
ibm_botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "None"
2019-10-27 13:49:01,478 [INFO] pywren_ibm_cloud.executor: ExecutorID 0b31-48da - Cleaning temporary data
```
and the activation c6d09489f6844645909489f684f64552 :
```
ok: got activation c6d09489f6844645909489f684f64552
{
    "namespace": "pywren_dev_us_east",
    "name": "omerb01_pywren-omer-runtime_3.6.16_2048MB",
    "version": "0.0.1",
    "subject": "Omer.Belhasin@ibm.com",
    "activationId": "c6d09489f6844645909489f684f64552",
    "start": 1572176722024,
    "end": 1572176785295,
    "duration": 63271,
    "statusCode": 0,
    "response": {
        "status": "success",
        "statusCode": 0,
        "success": true,
        "result": {
            "Execution": "Finished"
        }
    },
    "logs": [
        "2019-10-27T11:45:22.027485Z    stdout: [INFO] __main__: Starting IBM Cloud Functions execution",
        "2019-10-27T11:45:22.028148Z    stdout: [INFO] handler: Execution ID: 0b31-48da/M000/01385",
        "2019-10-27T11:45:22.034014Z    stdout: [INFO] JobRunner: Started",
        "2019-10-27T11:46:24.981342Z    stdout: ----------------------- EXCEPTION !-----------------------",
        "2019-10-27T11:46:24.991710Z    stdout: Traceback (most recent call last):",
        "2019-10-27T11:46:24.991728Z    stdout: File \"/usr/local/lib/python3.6/site-packages/urllib3/response.py\", line 425, in _error_catcher",
        "2019-10-27T11:46:24.991733Z    stdout: yield",
        "2019-10-27T11:46:24.991738Z    stdout: File \"/usr/local/lib/python3.6/site-packages/urllib3/response.py\", line 503, in read",
        "2019-10-27T11:46:24.991742Z    stdout: data = self._fp.read() if not fp_closed else b\"\"",
        "2019-10-27T11:46:24.991775Z    stdout: File \"/usr/local/lib/python3.6/http/client.py\", line 472, in read",
        "2019-10-27T11:46:24.991782Z    stdout: s = self._safe_read(self.length)",
        "2019-10-27T11:46:24.991786Z    stdout: File \"/usr/local/lib/python3.6/http/client.py\", line 622, in _safe_read",
        "2019-10-27T11:46:24.991791Z    stdout: chunk = self.fp.read(min(amt, MAXAMOUNT))",
        "2019-10-27T11:46:24.991795Z    stdout: File \"/usr/local/lib/python3.6/socket.py\", line 586, in readinto",
        "2019-10-27T11:46:24.991799Z    stdout: return self._sock.recv_into(b)",
        "2019-10-27T11:46:24.991804Z    stdout: File \"/usr/local/lib/python3.6/ssl.py\", line 1012, in recv_into",
        "2019-10-27T11:46:24.991808Z    stdout: return self.read(nbytes, buffer)",
        "2019-10-27T11:46:24.991813Z    stdout: File \"/usr/local/lib/python3.6/ssl.py\", line 874, in read",
        "2019-10-27T11:46:24.991817Z    stdout: return self._sslobj.read(len, buffer)",
        "2019-10-27T11:46:24.991821Z    stdout: File \"/usr/local/lib/python3.6/ssl.py\", line 631, in read",
        "2019-10-27T11:46:24.991825Z    stdout: v = self._sslobj.read(len, buffer)",
        "2019-10-27T11:46:24.991850Z    stdout: socket.timeout: The read operation timed out",
        "2019-10-27T11:46:24.991919Z    stdout: ",
        "2019-10-27T11:46:24.991928Z    stdout: During handling of the above exception, another exception occurred:",
        "2019-10-27T11:46:24.991932Z    stdout: ",
        "2019-10-27T11:46:24.991936Z    stdout: Traceback (most recent call last):",
        "2019-10-27T11:46:24.991972Z    stdout: File \"/usr/local/lib/python3.6/site-packages/ibm_botocore/response.py\", line 78, in read",
        "2019-10-27T11:46:24.991979Z    stdout: chunk = self._raw_stream.read(amt)",
        "2019-10-27T11:46:24.991984Z    stdout: File \"/usr/local/lib/python3.6/site-packages/urllib3/response.py\", line 529, in read",
        "2019-10-27T11:46:24.991988Z    stdout: raise IncompleteRead(self._fp_bytes_read, self.length_remaining)",
        "2019-10-27T11:46:24.992014Z    stdout: File \"/usr/local/lib/python3.6/contextlib.py\", line 99, in __exit__",
        "2019-10-27T11:46:24.992021Z    stdout: self.gen.throw(type, value, traceback)",
        "2019-10-27T11:46:24.992025Z    stdout: File \"/usr/local/lib/python3.6/site-packages/urllib3/response.py\", line 430, in _error_catcher",
        "2019-10-27T11:46:24.992029Z    stdout: raise ReadTimeoutError(self._pool, None, \"Read timed out.\")",
        "2019-10-27T11:46:24.992034Z    stdout: urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='s3.us.cloud-object-storage.appdomain.cloud', port=443): Read timed out.",
        "2019-10-27T11:46:24.992038Z    stdout: ",
        "2019-10-27T11:46:24.992042Z    stdout: During handling of the above exception, another exception occurred:",
        "2019-10-27T11:46:24.992046Z    stdout: ",
        "2019-10-27T11:46:24.992051Z    stdout: Traceback (most recent call last):",
        "2019-10-27T11:46:24.992084Z    stdout: File \"/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py\", line 234, in run",
        "2019-10-27T11:46:24.992090Z    stdout: loaded_func_all = self._get_function_and_modules()",
        "2019-10-27T11:46:24.992095Z    stdout: File \"/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py\", line 88, in _get_function_and_modules",
        "2019-10-27T11:46:24.992099Z    stdout: func_obj = self.internal_storage.get_func(self.func_key)",
        "2019-10-27T11:46:24.992194Z    stdout: File \"/action/pywren_ibm_cloud/storage/storage.py\", line 102, in get_func",
        "2019-10-27T11:46:24.992209Z    stdout: return self.storage_handler.get_object(self.bucket, key)",
        "2019-10-27T11:46:24.992214Z    stdout: File \"/action/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py\", line 150, in get_object",
        "2019-10-27T11:46:24.992219Z    stdout: data = r['Body'].read()",
        "2019-10-27T11:46:24.992223Z    stdout: File \"/usr/local/lib/python3.6/site-packages/ibm_botocore/response.py\", line 81, in read",
        "2019-10-27T11:46:24.992238Z    stdout: raise ReadTimeoutError(endpoint_url=e.url, error=e)",
        "2019-10-27T11:46:24.992271Z    stdout: ibm_botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: \"None\"",
        "2019-10-27T11:46:24.992278Z    stdout: ----------------------------------------------------------",
        "2019-10-27T11:46:24.994160Z    stdout: [INFO] JobRunner: Finished",
        "2019-10-27T11:46:25.009424Z    stdout: [INFO] handler: Storing execution stats - status.json - Size: 2.4KiB"
    ],
    "annotations": [
        {
            "key": "path",
            "value": "pywren_dev_us_east/pywren_v1.1.0/omerb01_pywren-omer-runtime_3.6.16_2048MB"
        },
        {
            "key": "waitTime",
            "value": 35
        },
        {
            "key": "kind",
            "value": "blackbox"
        },
        {
            "key": "timeout",
            "value": false
        },
        {
            "key": "limits",
            "value": {
                "concurrency": 1,
                "logs": 10,
                "memory": 2048,
                "timeout": 600000
            }
        }
    ],
    "publish": false
}
```

is there any way to avoid this behaviour  ?

**Comment by gilv** [comment]
@JosepSampe do you know how to prevent this timeout from COS? Are there open connections that we don't write / read them?

**Comment by gilv** [comment]
@JosepSampe it happens when we create thosands of invocations and then on read status - getting timeout reading from COS

**Comment by JosepSampe** [comment]
@gilv We have 1 connection open per function (in jobrunner.py) to read the function itself and the data. If you write **ibm_cos** parameter, then there are 2 open connections per function.

@omerb01 Did you create a function with the **ibm_cos** parameter? or are you manually setting connections to COS to read those 8 files?

**Comment by omerb01** [comment]
@JosepSampe with `ibm_cos`

**Comment by JosepSampe** [comment]
@gilv Maybe some limitation in COS about parallel read? @omerb01 Are you using the free tier? Maybe something related to the cross-region us endpoin? can you try using a regional container in us-east?

**Comment by omerb01** [comment]
@JosepSampe Thanks a lot , joined into a "standard" account and it seems ok.
