### ISSUE TITLE
CredentialRetrievalError in action

### ISSUE THREAD

**Issue by LachlanStuart** [pywren/pywren-ibm-cloud#241]
I see an intermittent exception inside actions with PyWren 1.3.0:
```
$ ibmcloud fn activation logs f07eccedf6c640e4beccedf6c600e4df
2019-12-17T16:48:01.307950Z    stdout: [INFO] __main__: Starting IBM Cloud Functions execution
2019-12-17T16:48:01.308840Z    stdout: [DEBUG] handler: Action handler started
2019-12-17T16:48:01.309551Z    stdout: [INFO] handler: Execution ID: aafcca/11/M004/00091
2019-12-17T16:48:01.309562Z    stdout: [DEBUG] handler: Set function execution timeout to 600s
2019-12-17T16:48:01.310299Z    stdout: [DEBUG] handler: Starting JobRunner process
2019-12-17T16:48:01.315553Z    stdout: [INFO] JobRunner: Started
2019-12-17T16:48:01.315965Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2019-12-17T16:48:01.316155Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.eu-de.cloud-object-storage.appdomain.cloud
2019-12-17T16:48:01.317160Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using IBM COS API Key - Reusing Token
2019-12-17T16:48:01.333025Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2019-12-17T16:48:01.333045Z    stdout: [DEBUG] JobRunner: Getting function and modules
2019-12-17T16:48:02.270779Z    stdout: [DEBUG] JobRunner: Finished getting Function and modules
2019-12-17T16:48:02.270798Z    stdout: [DEBUG] JobRunner: Writing Function dependencies to local disk
2019-12-17T16:48:02.272434Z    stdout: [DEBUG] JobRunner: Finished writing Function dependencies
2019-12-17T16:48:02.272447Z    stdout: [DEBUG] JobRunner: Unpickle Function
2019-12-17T16:48:02.616176Z    stdout: [DEBUG] JobRunner: Finished Function unpickle
2019-12-17T16:48:02.616216Z    stdout: [DEBUG] JobRunner: Getting function data
2019-12-17T16:48:02.631463Z    stdout: [DEBUG] JobRunner: Finished getting Function data
2019-12-17T16:48:02.631496Z    stdout: [DEBUG] JobRunner: Unpickle Function data
2019-12-17T16:48:02.631527Z    stdout: [DEBUG] JobRunner: Finished unpickle Function data
2019-12-17T16:48:02.631532Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2019-12-17T16:48:02.631536Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.eu-de.cloud-object-storage.appdomain.cloud
2019-12-17T16:48:02.635608Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using IBM COS API Key - Reusing Token
2019-12-17T16:48:02.638922Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2019-12-17T16:48:02.651683Z    stdout: [INFO] JobRunner: Getting dataset from ibm_cos://metaspace-lachlan-input/metabolomics/tmp/clipped_centroids_chunks/180.msgpack
2019-12-17T16:48:04.834526Z    stdout: ----------------------- EXCEPTION !-----------------------
2019-12-17T16:48:04.837278Z    stdout: Traceback (most recent call last):
2019-12-17T16:48:04.837466Z    stdout: File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 243, in run
2019-12-17T16:48:04.837472Z    stdout: self._create_data_stream(data)
2019-12-17T16:48:04.837490Z    stdout: File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 225, in _create_data_stream
2019-12-17T16:48:04.837494Z    stdout: obj.data_stream = storage_handler.get_object(obj.bucket, obj.key, stream=True)
2019-12-17T16:48:04.837560Z    stdout: File "/action/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 146, in get_object
2019-12-17T16:48:04.837566Z    stdout: r = self.cos_client.get_object(Bucket=bucket_name, Key=key, **extra_get_args)
2019-12-17T16:48:04.837583Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/client.py", line 357, in _api_call
2019-12-17T16:48:04.837587Z    stdout: return self._make_api_call(operation_name, kwargs)
2019-12-17T16:48:04.837654Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/client.py", line 648, in _make_api_call
2019-12-17T16:48:04.837660Z    stdout: operation_model, request_dict, request_context)
2019-12-17T16:48:04.837723Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/client.py", line 667, in _make_request
2019-12-17T16:48:04.837729Z    stdout: return self._endpoint.make_request(operation_model, request_dict)
2019-12-17T16:48:04.837742Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/endpoint.py", line 102, in make_request
2019-12-17T16:48:04.837747Z    stdout: return self._send_request(request_dict, operation_model)
2019-12-17T16:48:04.837809Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/endpoint.py", line 132, in _send_request
2019-12-17T16:48:04.837814Z    stdout: request = self.create_request(request_dict, operation_model)
2019-12-17T16:48:04.837877Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/endpoint.py", line 116, in create_request
2019-12-17T16:48:04.837882Z    stdout: operation_name=operation_model.name)
2019-12-17T16:48:04.837899Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/hooks.py", line 356, in emit
2019-12-17T16:48:04.837903Z    stdout: return self._emitter.emit(aliased_event_name, **kwargs)
2019-12-17T16:48:04.837976Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/hooks.py", line 228, in emit
2019-12-17T16:48:04.837982Z    stdout: return self._emit(event_name, kwargs)
2019-12-17T16:48:04.837994Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/hooks.py", line 211, in _emit
2019-12-17T16:48:04.837998Z    stdout: response = handler(**kwargs)
2019-12-17T16:48:04.838053Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/signers.py", line 90, in handler
2019-12-17T16:48:04.838058Z    stdout: return self.sign(operation_name, request)
2019-12-17T16:48:04.838072Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/signers.py", line 149, in sign
2019-12-17T16:48:04.838076Z    stdout: auth = self.get_auth_instance(**kwargs)
2019-12-17T16:48:04.838127Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/signers.py", line 229, in get_auth_instance
2019-12-17T16:48:04.838133Z    stdout: frozen_credentials = self._credentials.get_frozen_credentials()
2019-12-17T16:48:04.838195Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/credentials.py", line 2482, in get_frozen_credentials
2019-12-17T16:48:04.838200Z    stdout: token = self.token_manager.get_token()
2019-12-17T16:48:04.838241Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/credentials.py", line 2024, in get_token
2019-12-17T16:48:04.838262Z    stdout: self._get_initial_token()
2019-12-17T16:48:04.838289Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/credentials.py", line 2220, in _get_initial_token
2019-12-17T16:48:04.838294Z    stdout: metadata = self.auth_function()
2019-12-17T16:48:04.838338Z    stdout: File "/usr/local/lib/python3.6/site-packages/ibm_botocore/credentials.py", line 2109, in _default_auth_function
2019-12-17T16:48:04.838344Z    stdout: raise CredentialRetrievalError(provider=self._get_token_url(), error_msg=_msg)
2019-12-17T16:48:04.838445Z    stdout: ibm_botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from https://iam.cloud.ibm.com/identity/token: HttpCode(429) - Retrieval of tokens from server failed.
2019-12-17T16:48:04.838518Z    stdout: ----------------------------------------------------------
2019-12-17T16:48:04.838753Z    stdout: [DEBUG] JobRunner: Pickling exception
2019-12-17T16:48:04.840534Z    stdout: [INFO] JobRunner: Finished
2019-12-17T16:48:04.847509Z    stdout: [DEBUG] handler: JobRunner process finished
2019-12-17T16:48:04.848607Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2019-12-17T16:48:04.848667Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.eu-de.cloud-object-storage.appdomain.cloud
2019-12-17T16:48:04.849029Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using IBM COS API Key - Reusing Token
2019-12-17T16:48:04.856865Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2019-12-17T16:48:04.856933Z    stdout: [INFO] handler: Storing execution stats - status.json - Size: 5.4KiB
2019-12-17T16:48:04.990888Z    stdout: [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/aafcca/11/M004/00091/status.json - Size: 5.4KiB - OK
```

This happened using pywren-ibm-cloud 1.3.0. I'm using IAM-based authentication, with the same config file as I had in https://github.com/pywren/pywren-ibm-cloud/issues/237 .

**Comment by JosepSampe** [comment]
This seems to be related to #242
