### ISSUE TITLE
test fails after #260 merge

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#261]
======================================================================
ERROR: test_chunks_bucket_one_reducer_per_object (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 383, in test_chunks_bucket_one_reducer_per_object
    result = pw.get_result(futures)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 399, in get_result
    WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 357, in wait
    raise e
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 341, in wait
    THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/wait/wait_storage.py", line 86, in wait_storage
    THREADPOOL_SIZE=THREADPOOL_SIZE)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/wait/wait_storage.py", line 255, in _wait_storage
    pool.map(get_result, f_to_wait_on)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/wait/wait_storage.py", line 238, in get_result
    f.result(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/future.py", line 241, in result
    self.status(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/future.py", line 186, in status
    reraise(*self._exception)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/action/pywren_ibm_cloud/wait/wait_storage.py", line 286, in _future_timeout_checker_thread
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_internal_executions (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 289, in test_internal_executions
    result = pw.get_result()
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 399, in get_result
    WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 357, in wait
    raise e
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 341, in wait
    THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/wait/wait_storage.py", line 86, in wait_storage
    THREADPOOL_SIZE=THREADPOOL_SIZE)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/wait/wait_storage.py", line 255, in _wait_storage
    pool.map(get_result, f_to_wait_on)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/wait/wait_storage.py", line 238, in get_result
    f.result(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/future.py", line 241, in result
    self.status(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/future.py", line 186, in status
    reraise(*self._exception)
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/six.py", line 695, in reraise
    raise value.with_traceback(tb)
  File "/action/pywren_ibm_cloud/runtime/function_handler/jobrunner.py", line 252, in run
  File "pywren_ibm_cloud/tests.py", line 102, in pywren_inside_pywren_map_function
    return pw.get_result()
  File "/action/pywren_ibm_cloud/executor.py", line 399, in get_result
  File "/action/pywren_ibm_cloud/executor.py", line 357, in wait
  File "/action/pywren_ibm_cloud/executor.py", line 341, in wait
  File "/action/pywren_ibm_cloud/wait/wait_storage.py", line 86, in wait_storage
  File "/action/pywren_ibm_cloud/wait/wait_storage.py", line 255, in _wait_storage
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
  File "/action/pywren_ibm_cloud/wait/wait_storage.py", line 238, in get_result
  File "/action/pywren_ibm_cloud/future.py", line 241, in result
  File "/action/pywren_ibm_cloud/future.py", line 186, in status
  File "/usr/local/lib/python3.6/site-packages/six.py", line 702, in reraise
  File "/action/pywren_ibm_cloud/wait/wait_storage.py", line 286, in _future_timeout_checker_thread
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
Ran 14 tests in 228.121s

FAILED (errors=2)
gilv1-mac:pywren-ibm-cloud gilv$ 

@JosepSampe can you check it please?

**Comment by JosepSampe** [comment]
@gilv all tests run ok for me.  Did you update runtimes?

**Comment by gilv** [comment]
@JosepSampe nope...just used new code without update runtimes

**Comment by gilv** [comment]
@omerb01 we need to update the runtime.

**Comment by omerb01** [comment]
@gilv @JosepSampe which Dockerfile should I need to use?

**Comment by gilv** [comment]
@omerb01 create new image...Docker file the same

**Comment by JosepSampe** [comment]
Seems that even having the runtime updated, from sometimes this issue appears in 1 of each 20 pywren executions. #262 Fixes it.
