### ISSUE TITLE
Get authentication invalid error

### ISSUE THREAD

**Issue by tokamo10** [pywren/pywren-ibm-cloud#267]
I am just try to do the following tutorial: https://developer.ibm.com/tutorials/quickly-run-python-code-at-scale/
When I run the python file(word_counter.py), I get an error. Where should I check?
```
root@icossd01:~#  python3 word_counter.py
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
PyWren v1.4.3-SNAPSHOT init for IBM Cloud Functions - Namespace: namespace_iam - Region: us_south
ExecutorID 8160aa/0 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB (Installing...)
Traceback (most recent call last):
  File "word_counter.py", line 34, in <module>
    pw.map_reduce(my_map_function, bucketname, my_reduce_function, chunk_size)
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud-1.4.3_SNAPSHOT-py3.6.egg/pywren_ibm_cloud/executor.py", line 226, in map_reduce
    runtime_meta = self.invoker.select_runtime(map_job_id, map_runtime_memory)
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud-1.4.3_SNAPSHOT-py3.6.egg/pywren_ibm_cloud/invoker.py", line 117, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud-1.4.3_SNAPSHOT-py3.6.egg/pywren_ibm_cloud/compute/compute.py", line 46, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud-1.4.3_SNAPSHOT-py3.6.egg/pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py", line 174, in create_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name)
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud-1.4.3_SNAPSHOT-py3.6.egg/pywren_ibm_cloud/compute/backends/ibm_cf/ibm_cf.py", line 280, in _generate_runtime_meta
    memory=runtime_memory, timeout=30000)
  File "/usr/local/lib/python3.6/dist-packages/pywren_ibm_cloud-1.4.3_SNAPSHOT-py3.6.egg/pywren_ibm_cloud/libs/openwhisk/client.py", line 103, in create_action
    raise Exception(msg)
Exception: An error occurred creating/updating action ibmfunctions_action-python-v3.6_128MB: The supplied authentication is invalid
root@icossd01:~#
```
When I run the following code, same error was happened.
```
import pywren_ibm_cloud as pywren

def add_seven(x):
    return x + 7

if __name__ == '__main__':
    ibmcf = pywren.ibm_cf_executor()
    ibmcf.call_async(add_seven, 3)
    print(ibmcf.get_result())
```

**Comment by JosepSampe** [comment]
@tokamo10 Verify you got the correct IBM CF key here; https://cloud.ibm.com/functions/namespace-settings. Detailed Config instructions re here: https://github.com/pywren/pywren-ibm-cloud/tree/master/config

**Comment by tokamo10** [comment]
@JosepSampe I was using IAM-based namespace and set "IAM API key" in api_key of ibm_cf.
So I change CF-based namespace and set "CF-based API key", it works fine.
Thank you!
