### ISSUE TITLE
Dockerfile runtime build issue

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#272]
I think that I observe issues with the base Dockerfile shared here in the repository.
it seems to be an old bug, I have discovered that after enforcing Docker for don't use cache in the process of creating the new runtime.

I get the following error in the process of creating a new runtime:
```
ERROR: ibm-cos-sdk-core 2.6.0 has requirement requests<2.23,>=2.18, but you'll have requests 2.23.0 which is incompatible.
```
it seems that this error causes some damage for the runtime so when I use COS, I observe (for example):
![image (1)](https://user-images.githubusercontent.com/13593227/77563096-81008c00-6ec9-11ea-960d-53591662052b.png)

any ideas why that happens? when I use my old runtime, it works, but I can't recreate it again.

**Comment by omerb01** [comment]
also, I'm not sure what is `entry_point.py` and how it should be integrated with my custom runtime, do I have to hold this file in my project as a PyWren user?

**Comment by JosepSampe** [comment]
Which dockerfile are you using?

**Comment by omerb01** [comment]
@JosepSampe I use the slim Dockerfile for CF, I'm not sure that "requests" module is exactly the problem, I fixed it by enforcing docker to install requests version 2.22 . 
more example errors:
```
Traceback (most recent call last):
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/response.py", line 438, in read
    data = self._fp.read()
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(42205184 bytes read, 377343775 more expected)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-79872d5ce80b>", line 1, in <module>
    runfile('/home/omerbelh/pywren-annotation-pipeline/scripts/run_pipeline.py', wdir='/home/omerbelh/pywren-annotation-pipeline')
  File "/home/omerbelh/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/omerbelh/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/omerbelh/pywren-annotation-pipeline/scripts/run_pipeline.py", line 23, in <module>
    pipeline()
  File "/home/omerbelh/pywren-annotation-pipeline/annotation_pipeline/pipeline.py", line 40, in __call__
    self.segment_ds()
  File "/home/omerbelh/pywren-annotation-pipeline/annotation_pipeline/pipeline.py", line 62, in segment_ds
    self.ds_segments_bounds, self.ds_segm_size_mb, self.imzml_parser.mzPrecision)
  File "/home/omerbelh/pywren-annotation-pipeline/annotation_pipeline/segment.py", line 137, in segment_spectra
    pw.get_result(first_futures)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/executor.py", line 399, in get_result
    WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/executor.py", line 357, in wait
    raise e
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/executor.py", line 341, in wait
    THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/wait/wait_storage.py", line 86, in wait_storage
    THREADPOOL_SIZE=THREADPOOL_SIZE)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/wait/wait_storage.py", line 255, in _wait_storage
    pool.map(get_result, f_to_wait_on)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/wait/wait_storage.py", line 238, in get_result
    f.result(throw_except=throw_except, internal_storage=internal_storage)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/future.py", line 241, in result
    self.status(throw_except=throw_except, internal_storage=internal_storage)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/future.py", line 139, in status
    self._call_status = internal_storage.get_call_status(self.executor_id, self.job_id, self.call_id)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/storage/storage.py", line 163, in get_call_status
    data = self.storage_handler.get_object(self.bucket, status_key)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud-1.4.2-py3.6.egg/pywren_ibm_cloud/storage/backends/ibm_cos/ibm_cos.py", line 176, in get_object
    data = r['Body'].read()
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ibm_cos_sdk_core-2.6.0-py3.6.egg/ibm_botocore/response.py", line 78, in read
    chunk = self._raw_stream.read(amt)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(42205184 bytes read, 377343775 more expected)', IncompleteRead(42205184 bytes read, 377343775 more expected))
```

**Comment by JosepSampe** [comment]
Maybe this is related to #271

**Comment by omerb01** [comment]
@JosepSampe I don't think so, it happens only when I use a new runtime with the same dependencies as before

**Comment by JosepSampe** [comment]
I need some simple function to replicate the issue, if not it is almost impossible to know what is going wrong in this case ;)

**Comment by omerb01** [comment]
@JosepSampe my bad, it seems that you are right about #271 and I actually get a different error that is related to my additional dependencies. thanks.

**Comment by JosepSampe** [comment]
These days working from home we are all experiencing same connection issues ;)
