### ISSUE TITLE
Pull request #270  - tests doesn't pass

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#273]
@JosepSampe @omerb01 can you check it please?
Happened when i merged #270 

======================================================================
FAIL: test_call_async (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 211, in test_call_async
    self.assertEqual(result, "Hello World!")
AssertionError: ['Hello World!'] != 'Hello World!'

======================================================================
FAIL: test_chunks_bucket (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 368, in test_chunks_bucket
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: [291130] != 291130

======================================================================
FAIL: test_cloudobject (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 401, in test_cloudobject
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: [291130] != 291130

======================================================================
FAIL: test_internal_executions (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 291, in test_internal_executions
    self.assertEqual(result, [0] + [list(range(i)) for i in range(2, 11)])
AssertionError: Lists differ: [[0], [0, 1], [0, 1, 2], [0, 1, 2, 3], [0,[138 chars], 9]] != [0, [0, 1], [0, 1, 2], [0, 1, 2, 3], [0, 1[136 chars], 9]]

First differing element 0:
[0]
0

- [[0],
? -  -

+ [0,
   [0, 1],
   [0, 1, 2],
   [0, 1, 2, 3],
   [0, 1, 2, 3, 4],
   [0, 1, 2, 3, 4, 5],
   [0, 1, 2, 3, 4, 5, 6],
   [0, 1, 2, 3, 4, 5, 6, 7],
   [0, 1, 2, 3, 4, 5, 6, 7, 8],
   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

======================================================================
FAIL: test_map_reduce (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 260, in test_map_reduce
    self.assertEqual(result, 20)
AssertionError: [20] != 20

======================================================================
FAIL: test_map_reduce_cos_bucket (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 312, in test_map_reduce_cos_bucket
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: [291130] != 291130

======================================================================
FAIL: test_map_reduce_cos_key (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 332, in test_map_reduce_cos_key
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: [291130] != 291130

======================================================================
FAIL: test_map_reduce_url (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 350, in test_map_reduce_url
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: [291130] != 291130

======================================================================
FAIL: test_storage_handler (__main__.TestPywren)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pywren_ibm_cloud/tests.py", line 358, in test_storage_handler
    self.assertEqual(result, self.__class__.cos_result_to_compare)
AssertionError: [291130] != 291130

----------------------------------------------------------------------
Ran 14 tests in 322.444s

FAILED (failures=9)

**Comment by JosepSampe** [comment]
Fixing it...

**Comment by gilv** [comment]
@JosepSampe thanks
