### ISSUE TITLE
issues regarding Knative backhand

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#277]
We found some bugs when using PyWren over Knative:
1. "private_endpoint" key error:
```
Traceback (most recent call last):
  File "omer.py", line 7, in <module>
    kn = pywren.knative_executor()
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/__init__.py", line 59, in knative_executor
    log_level=log_level
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 83, in __init__
    self.config = default_config(copy.deepcopy(config), pw_config_ow)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/config.py", line 129, in default_config
    sb_config.load_config(config_data)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/storage/backends/ibm_cos/config.py", line 30, in load_config
    if not config_data['ibm_cos']['private_endpoint'].startswith('http'):
KeyError: 'private_endpoint'
```
I assume the problem is inside:
https://github.com/pywren/pywren-ibm-cloud/blob/9576dc0722b8c87cda4acf096a9423a9169788e3/pywren_ibm_cloud/storage/backends/ibm_cos/config.py#L11-L12
2. default runtime has extra tag extension to its name:
```
PyWren v1.5.0 init for Knative - Endpoint: http://10.126.111.28:31380
ExecutorID bc3a28/0 | JobID A000 - Selected Runtime: omerb01/pywren-knative-v36:1.5.0 - 256MB (Installing...)
Traceback (most recent call last):
  File "omer.py", line 8, in <module>
    kn.call_async(my_function, 3)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 131, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/invoker.py", line 118, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/compute.py", line 46, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/backends/knative/knative.py", line 396, in create_runtime
    self._create_service(docker_image_name, memory, timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/backends/knative/knative.py", line 333, in _create_service
    body=svc_res
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/api/custom_objects_api.py", line 183, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/api/custom_objects_api.py", line 289, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/api_client.py", line 388, in request
    body=body)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/rest.py", line 278, in POST
    body=body)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/kubernetes-11.0.0-py3.6.egg/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 30 Mar 2020 16:35:50 GMT', 'Content-Length': '495'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"validation.webhook.serving.knative.dev\" denied the request: validation failed: not a DNS 1035 label: [a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]: metadata.name","reason":"BadRequest","code":400}
```
in Kubernetes cluster I think there shouldn't be any extentions to Docker images, i.e `omerb01/pywren-knative-v36:1.5.0` should be `omerb01/pywren-knative-v36-1.5.0` or `omerb01/pywren-knative-v36`

**Comment by JosepSampe** [comment]
Re. first issue, I will add a fix.
Re. second issue, for now it is better to not to provide version numbers. In fact what fails are the points '.', so don't include points in the docker image, for example this will work: `omerb01/pywren-knative-v36:150`
