### ISSUE TITLE
default Knative runtime can't be installed

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#283]
when I try to run PyWren over Knative with the default runtime, I get:
```
2020-04-02 11:17:23,792 [INFO] pywren_ibm_cloud.config: PyWren v1.5.2-SNAPSHOT
2020-04-02 11:17:23,792 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-04-02 11:17:23,792 [INFO] pywren_ibm_cloud.config: Getting configuration from /home/omerbelh/.pywren_config
2020-04-02 11:17:23,871 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: knative
2020-04-02 11:17:24,153 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: ibm_cos
2020-04-02 11:17:24,211 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: ac178b/0
2020-04-02 11:17:24,211 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-04-02 11:17:24,211 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-04-02 11:17:24,211 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-04-02 11:17:24,234 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-04-02 11:17:24,234 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ac178b/0 - Total available workers: 256
2020-04-02 11:17:24,256 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Loaded service host suffix: .default.example.com
2020-04-02 11:17:24,256 [INFO] pywren_ibm_cloud.compute.backends.knative.knative: PyWren v1.5.2-SNAPSHOT init for Knative - Endpoint: http://10.126.111.28:31380
2020-04-02 11:17:24,256 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ac178b/0 - Creating function invoker
2020-04-02 11:17:24,259 [INFO] pywren_ibm_cloud.invoker: ExecutorID ac178b/0 | JobID A000 - Selected Runtime: omerb01/pywren-knative-v36:latest - 256MB
2020-04-02 11:17:24,259 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in local cache. Retrieving it from storage
2020-04-02 11:17:24,945 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ac178b/0 | JobID A000 - Runtime omerb01/pywren-knative-v36:latest with 256MB is not yet installed
2020-04-02 11:17:24,945 [DEBUG] pywren_ibm_cloud.invoker: Creating runtime: omerb01/pywren-knative-v36:latest, memory: 256MB
2020-04-02 11:17:24,945 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Creating PyWren runtime service resource in k8s
```
I assume that there is no "omerb01/pywren-knative-v36" image , I think it should be under a preprocessed account as much like "ibmfunctions" account.
when I switch the runtime for a custom made runtime, everything works.

**Comment by JosepSampe** [comment]
The first time you run a function, without a custom runtime, Pywren uses tekton to build the default runtime by using your k8s cluster and pushes it into your docker hub account.

Do you set docker usernane and token in your pywren config file?

**Comment by omerb01** [comment]
@JosepSampe yes, as I said above - with my custom made runtime, everything works

**Comment by JosepSampe** [comment]
Which kind of kubernetes cluster do you have? do you have tekton installed?

**Comment by omerb01** [comment]
@JosepSampe I used the installation script that you mentioned in docs, so I assume that I have tekton installed

**Comment by JosepSampe** [comment]
Ok, if you used that script it is supposed to be installed. You can check it by running: `kubectl get pods --namespace tekton-pipelines`. If it shows 2 pods in running state everything is ok.

To check what is happening, clean everything with `pywren-ibm-cloud clean`. Then run this command in another terminal: `watch kubectl get pod,revision,service,deployment -o wide` to monitor pod creation. An finally execute a pywren job and check if build pod is created, and if it shows error or not.

**Comment by JosepSampe** [comment]
I think I already found the source of the issue. Checking it...

**Comment by omerb01** [comment]
@gilv can you reopen the issue?

@JosepSampe I still get an error, maybe I do something wrong:
```
omerbelh@pywren:~$ python omer.py
2020-04-05 10:23:32,275 [INFO] pywren_ibm_cloud.config: PyWren v1.5.2-SNAPSHOT
2020-04-05 10:23:32,275 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-04-05 10:23:32,275 [INFO] pywren_ibm_cloud.config: Getting configuration from /home/omerbelh/.pywren_config
2020-04-05 10:23:32,355 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: knative
2020-04-05 10:23:32,648 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: ibm_cos
2020-04-05 10:23:32,710 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: b884cc/0
2020-04-05 10:23:32,710 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-04-05 10:23:32,710 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-04-05 10:23:32,710 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-04-05 10:23:32,734 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-04-05 10:23:32,734 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID b884cc/0 - Total available workers: 256
2020-04-05 10:23:32,756 [INFO] pywren_ibm_cloud.compute.backends.knative.knative: PyWren v1.5.2-SNAPSHOT init for Knative - Endpoint: http://10.126.111.28:31380
2020-04-05 10:23:32,756 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID b884cc/0 - Creating function invoker
2020-04-05 10:23:32,759 [INFO] pywren_ibm_cloud.invoker: ExecutorID b884cc/0 | JobID A000 - Selected Runtime: omerb01/pywren-knative-v36:latest - 256MB
2020-04-05 10:23:32,759 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in local cache. Retrieving it from storage
2020-04-05 10:23:33,275 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID b884cc/0 | JobID A000 - Runtime omerb01/pywren-knative-v36:latest with 256MB is not yet installed
2020-04-05 10:23:33,275 [DEBUG] pywren_ibm_cloud.invoker: Creating runtime: omerb01/pywren-knative-v36:latest, memory: 256MB
2020-04-05 10:23:33,275 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Building default docker image from git
2020-04-05 10:23:33,278 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Creating Account resources: Secret and ServiceAccount
2020-04-05 10:23:33,298 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Creating Build resources: PipelineResource and Task
2020-04-05 10:23:33,306 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Setting git url to: https://github.com/pywren/pywren-ibm-cloud
2020-04-05 10:23:33,306 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Setting git rev to: master
2020-04-05 10:23:33,340 [DEBUG] pywren_ibm_cloud.compute.backends.knative.knative: Building image...
Traceback (most recent call last):
  File "omer.py", line 8, in <module>
    kn.call_async(my_function, 3)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 129, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/invoker.py", line 118, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/compute.py", line 46, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/backends/knative/knative.py", line 395, in create_runtime
    self._build_default_runtime_from_git(default_runtime_img_name)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/compute/backends/knative/knative.py", line 285, in _build_default_runtime_from_git
    raise Exception('Unable to create the Docker image from the git repository')
Exception: Unable to create the Docker image from the git repository
```

@JosepSampe another thing I would like to discuss is the difference between CF and Knative backhand, I know that we use a default docker account called "ibmfunctions", but with Knative we build automatically a new runtime on the local account. is it possible to be aligned with CF approach so the same backhand would behave the same (maybe in using 2 different images in the default account).

**Comment by JosepSampe** [comment]
@omerb01 Can you provide logs from `pod/image-from-git` ?

**Comment by omerb01** [comment]
@JosepSampe 
```
{"level":"info","ts":1586116480.4552753,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/05 19:54:52 Skipping step because a previous step failed
```
also, reproduced a docker token and it outputed the same error

**Comment by JosepSampe** [comment]
What is the output if you write only  `kubectl logs image-from-git-xxx`?

**Comment by omerb01** [comment]
```
omerbelh@pywren:~$ kubectl get pod
NAME                       READY   STATUS   RESTARTS   AGE
image-from-git-pod-625rp   0/2     Error    0          27s
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp
error: a container name must be specified for pod image-from-git-pod-625rp, choose one of: [step-git-source-pywren-git-r2w7v step-build-and-push] or one of the init containers: [credential-initializer place-tools]
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c place-tools
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c credential-initializer
{"level":"info","ts":1586117068.9111545,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
{"level":"info","ts":1586117068.9119864,"logger":"fallback-logger","caller":"creds-init/main.go:42","msg":"Credentials initialized."}
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c credential-initializer -c step-git-source-pywren-git-r2w7v 
{"level":"info","ts":1586117070.9718874,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
{"level":"info","ts":1586117071.9822457,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
{"level":"error","ts":1586117079.6295393,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin master]: exit status 128\nfatal: unable to access 'https://github.com/pywren/pywren-ibm-cloud/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:90\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"error","ts":1586117085.0923693,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [pull --recurse-submodules=yes origin]: exit status 1\nfatal: unable to access 'https://github.com/pywren/pywren-ibm-cloud/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:93\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"warn","ts":1586117085.0924954,"logger":"fallback-logger","caller":"git/git.go:94","msg":"Failed to pull origin : exit status 1"}
{"level":"error","ts":1586117085.0963821,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [checkout master]: exit status 1\nerror: pathspec 'master' did not match any file(s) known to git\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:96\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"fatal","ts":1586117085.0964198,"logger":"fallback-logger","caller":"git-init/main.go:52","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:203"}
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c credential-initializer -c step-git-source-pywren-git-r2w7v -c step-build-and-push
{"level":"info","ts":1586117071.311175,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/05 20:04:45 Skipping step because a previous step failed
```

**Comment by omerb01** [comment]
```
omerbelh@pywren:~$ kubectl get pod
NAME                       READY   STATUS   RESTARTS   AGE
image-from-git-pod-625rp   0/2     Error    0          5m12s
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp
error: a container name must be specified for pod image-from-git-pod-625rp, choose one of: [step-git-source-pywren-git-r2w7v step-build-and-push] or one of the init containers: [credential-initializer place-tools]
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c step-git-source-pywren-git-r2w7v
{"level":"info","ts":1586117070.9718874,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
{"level":"info","ts":1586117071.9822457,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
{"level":"error","ts":1586117079.6295393,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin master]: exit status 128\nfatal: unable to access 'https://github.com/pywren/pywren-ibm-cloud/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:90\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"error","ts":1586117085.0923693,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [pull --recurse-submodules=yes origin]: exit status 1\nfatal: unable to access 'https://github.com/pywren/pywren-ibm-cloud/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:93\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"warn","ts":1586117085.0924954,"logger":"fallback-logger","caller":"git/git.go:94","msg":"Failed to pull origin : exit status 1"}
{"level":"error","ts":1586117085.0963821,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [checkout master]: exit status 1\nerror: pathspec 'master' did not match any file(s) known to git\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:96\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"fatal","ts":1586117085.0964198,"logger":"fallback-logger","caller":"git-init/main.go:52","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:203"}
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c step-build-and-push
{"level":"info","ts":1586117071.311175,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/05 20:04:45 Skipping step because a previous step failed
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c credential-initializer
{"level":"info","ts":1586117068.9111545,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
{"level":"info","ts":1586117068.9119864,"logger":"fallback-logger","caller":"creds-init/main.go:42","msg":"Credentials initialized."}
omerbelh@pywren:~$ kubectl logs image-from-git-pod-625rp -c place-tools
omerbelh@pywren:~$ 
```

**Comment by JosepSampe** [comment]
Seems in your case your container can't access internet, or you have dns problems, but not related to pywren.
```
{"level":"error","ts":1586117079.6295393,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin master]: exit status 128\nfatal: unable to access 'https://github.com/pywren/pywren-ibm-cloud/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:90\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
{"level":"error","ts":1586117085.0923693,"logger":"fallback-logger","caller":"git/git.go:41","msg":"Error running git [pull --recurse-submodules=yes origin]: exit status 1\nfatal: unable to access 'https://github.com/pywren/pywren-ibm-cloud/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:93\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:51\nruntime.main\n\truntime/proc.go:203"}
```
What kind of k8s installation do you have?

**Comment by omerb01** [comment]
@JosepSampe I am running it from within a VM of ubunto 18 with a minikube cluster

**Comment by gilv** [comment]
@omerb01 what is the status of it?

**Comment by omerb01** [comment]
@gilv still observe the same error, I'm not sure why I succeed to build custom made runtimes, but don't able to build the default one.

**Comment by JosepSampe** [comment]
In a previous PR I added more debug logs in the knative backend. Now errors from tekton should be printed in the pywren execution, so there is no need to run `kubectl logs image-from-git -c ...` to know what failed.

So, do you see these logs? and, are they showing the same _'Could not resolve host: github.com'_ issue?

**Comment by omerb01** [comment]
Thanks, works :)
