### ISSUE TITLE
cloudobjects features suggestion

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#300]
in recent PR's I saw that we have now `ibm_cos.put_cobject()` and `ibm_cos.get_cobject()`. I have 2 regarding suggestions:

1. To add a delete method for cobjects with `ibm_cos`, it will come in handy when we can delete a bunch of cobjects that we dont need anymore during an already running process. it can be called for example: `ibm_cos.delete_cobject()` or the equivalent method for a bunch of cobjects to delete: `ibm_cos.delete_cobjects()`.

2. To add equivalent methods `ibm_cos.put_cobjects()` and `ibm_cos.get_cobjects()` that will handle a list of cobject while using threads in an efficient way.

what do you think?

**Comment by omerb01** [comment]
another regarding suggestion that I have just thought about:
I would like to operate `map()` on a bunch of cobjects with the same way we use `obj` with a bunch of keys.

for example, I would like that the following code approach will run successfully:
```python
import pywren_ibm_cloud as pywren
pw = pywren.function_executor()

def my_func1(args, storage):
    return storage.put_cobject(b'data')

def my_func2(obj):
    return obj.data_stream.read()

pw.map(my_func1, range(3))
cobjs = pw.get_result()

pw.map(my_func2, cobjs)
results = pw.get_result()
print(results)
```

**Comment by JosepSampe** [comment]
Regarding the first post:
1. I already added these methods and I'm doing final tests. However, take into account that delete `cobjects` within a function is time consuming, and IMO it is preferable to delete the `cobjects` at the end of the script with `pw.clean()`
2. Based on my experience, we shouldn't create these methods. Using threads to get objects from COS might be faster when you invoke few function activations, but when you increase the number of function activations, there is no improvement of using threads to get multiple objects. So I think we should let users decide how to get multiple `cobjects`

Regarding the second post, it sounds really good, I will add it

**Comment by omerb01** [comment]
@JosepSampe Thanks!
Thought about another thing ;)
is it possible to add for `storage.get_object()` a param for getting a stream instead of the data? (the default value will be "false")

some kind of:
```python
data = storage.get_object(stream=True)
```
I have just noticed that I need it for advanced read methods.

**Comment by JosepSampe** [comment]
Yes, I can add it, that's easy ;)

**Comment by omerb01** [comment]
@JosepSampe Thanks

**Comment by omerb01** [comment]
@JosepSampe 
actually, I tested "stream" parameter with the following code:
```python
import pywren_ibm_cloud as pywren
pw = pywren.function_executor(log_level='DEBUG')

def my_func(args, storage):
    return storage.put_cobject(b'data')

pw.map(my_func, range(1))
cobjs = pw.get_result()

def my_func(cobject, storage):
    data_stream = storage.get_cobject(cobject, stream=True)
    return data_stream.read()

pw.map(my_func, cobjs)
print(pw.get_result())
```
and got the following exception:
```
2020-05-14 19:12:04,762 [INFO] pywren_ibm_cloud.config: PyWren v1.5.3-SNAPSHOT
2020-05-14 19:12:04,809 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-05-14 19:12:04,810 [INFO] pywren_ibm_cloud.config: Getting configuration from /Users/omerbelh/.pywren_config
2020-05-14 19:12:04,830 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: ibm_cf
2020-05-14 19:12:04,853 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: ibm_cos
2020-05-14 19:12:04,887 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: ea00fc/0
2020-05-14 19:12:04,887 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-05-14 19:12:04,887 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-05-14 19:12:04,887 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-05-14 19:12:04,934 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-05-14 19:12:04,934 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Total available workers: 256
2020-05-14 19:12:04,934 [DEBUG] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: Creating IBM Cloud Functions client
2020-05-14 19:12:04,934 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: Set IBM CF Namespace to pywren_dev_us_east
2020-05-14 19:12:04,934 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: Set IBM CF Endpoint to https://us-east.functions.cloud.ibm.com
2020-05-14 19:12:04,935 [INFO] pywren_ibm_cloud.compute.backends.ibm_cf.ibm_cf: IBM CF client created successfully
2020-05-14 19:12:04,935 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Creating function invoker
2020-05-14 19:12:04,948 [INFO] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M000 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB
2020-05-14 19:12:04,948 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata found in local cache
2020-05-14 19:12:04,948 [DEBUG] pywren_ibm_cloud.job.job: ExecutorID ea00fc/0 | JobID M000 - Serializing function and data
2020-05-14 19:12:04,950 [DEBUG] pywren_ibm_cloud.job.serialize: Referenced modules: {'/Users/omerbelh/PycharmProjects/pywren-temp/pywren.py'}
2020-05-14 19:12:04,951 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: None
2020-05-14 19:12:04,951 [INFO] pywren_ibm_cloud.job.job: ExecutorID ea00fc/0 | JobID M000 - Uploading function and data - Total: 610.0B
2020-05-14 19:12:05,882 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/ea00fc/0/M000/aggdata.pickle - Size: 24.0B - OK
2020-05-14 19:12:06,203 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/ea00fc/0/M000/func.pickle - Size: 586.0B - OK
2020-05-14 19:12:06,213 [INFO] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M000 - Starting function invocation: my_func()  - Total: 1 activations
2020-05-14 19:12:06,213 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M000 - Free workers: 256 - Going to invoke 1 function activations
2020-05-14 19:12:06,214 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 0 started
2020-05-14 19:12:06,216 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 1 started
2020-05-14 19:12:06,321 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M000 - Starting job monitoring
2020-05-14 19:12:06,322 [INFO] pywren_ibm_cloud.executor: ExecutorID ea00fc/0 - Getting results...
2020-05-14 19:12:06,923 [INFO] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M000 - Function call 00000 done! (0.708s) - Activation ID: 8b3248f0c6a3468eb248f0c6a3268e60
2020-05-14 19:12:08,235 [INFO] pywren_ibm_cloud.future: ExecutorID ea00fc/0 | JobID M000 - Got status from call 00000 - Activation ID: 8b3248f0c6a3468eb248f0c6a3268e60 - Time: 0.22 seconds
2020-05-14 19:12:08,409 [INFO] pywren_ibm_cloud.future: ExecutorID ea00fc/0 | JobID M000 - Got output from call 00000 - Activation ID: 8b3248f0c6a3468eb248f0c6a3268e60
2020-05-14 19:12:08,432 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Stopping invoker
2020-05-14 19:12:08,434 [INFO] pywren_ibm_cloud.executor: ExecutorID ea00fc/0 - Cleaning temporary data
2020-05-14 19:12:08,434 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 0 finished
2020-05-14 19:12:08,435 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 1 finished
2020-05-14 19:12:08,446 [DEBUG] pywren_ibm_cloud.executor: ExecutorID ea00fc/0 Finished getting results
2020-05-14 19:12:08,446 [INFO] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M001 - Selected Runtime: ibmfunctions/action-python-v3.6 - 256MB
2020-05-14 19:12:08,447 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata found in local cache
2020-05-14 19:12:08,448 [DEBUG] pywren_ibm_cloud.job.job: ExecutorID ea00fc/0 | JobID M001 - Serializing function and data
2020-05-14 19:12:08,451 [DEBUG] pywren_ibm_cloud.job.serialize: Referenced modules: {'/Users/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/storage/utils.py', '/Users/omerbelh/PycharmProjects/pywren-temp/pywren.py'}
2020-05-14 19:12:08,451 [DEBUG] pywren_ibm_cloud.job.serialize: Modules to transmit: None
2020-05-14 19:12:08,451 [INFO] pywren_ibm_cloud.job.job: ExecutorID ea00fc/0 | JobID M001 - Uploading function and data - Total: 814.0B
2020-05-14 19:12:08,819 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/ea00fc/0/M001/aggdata.pickle - Size: 185.0B - OK
2020-05-14 19:12:09,155 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: PUT Object pywren.jobs/ea00fc/0/M001/func.pickle - Size: 629.0B - OK
2020-05-14 19:12:09,160 [INFO] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M001 - Starting function invocation: my_func()  - Total: 1 activations
2020-05-14 19:12:09,161 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M001 - Free workers: 256 - Going to invoke 1 function activations
2020-05-14 19:12:09,163 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 0 started
2020-05-14 19:12:09,165 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 1 started
2020-05-14 19:12:09,263 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M001 - Starting job monitoring
2020-05-14 19:12:09,264 [INFO] pywren_ibm_cloud.executor: ExecutorID ea00fc/0 - Getting results...
2020-05-14 19:12:09,816 [INFO] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 | JobID M001 - Function call 00000 done! (0.654s) - Activation ID: 73044ca6586341ca844ca65863d1ca9d
2020-05-14 19:12:11,438 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Stopping invoker
2020-05-14 19:12:11,439 [INFO] pywren_ibm_cloud.executor: ExecutorID ea00fc/0 - Cleaning temporary data
2020-05-14 19:12:11,439 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 0 finished
2020-05-14 19:12:11,440 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID ea00fc/0 - Invoker process 1 finished
2020-05-14 19:12:11,451 [INFO] pywren_ibm_cloud.future: ExecutorID ea00fc/0 | JobID M001 - There was an exception - Activation ID: 73044ca6586341ca844ca65863d1ca9d
Traceback (most recent call last):
  File "/action/pywren_ibm_cloud/function/jobrunner.py", line 252, in run
  File "/Users/omerbelh/PycharmProjects/pywren-temp/pywren.py", line 12, in my_func
    return data_stream.read()
AttributeError: 'bytes' object has no attribute 'read'
```

**Comment by omerb01** [comment]
@JosepSampe Thanks, tested and it works :)
