### ISSUE TITLE
PyWren can't map a list of lists

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#301]
I found a bug that raises an unexpected exception when trying to put a list of lists as an input for pywren's `map()` method.

for example:
```python
import pywren_ibm_cloud as pywren

def my_func(list_input):
    return list_input

pw = pywren.function_executor()
pw.map(my_func, [[1, 2], [3, 4]])
print(pw.get_result())
```
this code should print `[[1, 2], [3, 4]]` but the actual result is:
```
Traceback (most recent call last):
  File "/Users/omerbelhasin/PycharmProjects/pywren-temp/pywren.py", line 7, in <module>
    pw.map(my_func, [[1, 2], [3, 4]])
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 179, in map
    execution_timeout=timeout)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/job/job.py", line 27, in create_map_job
    map_iterdata = utils.verify_args(map_function, iterdata, extra_params)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/utils.py", line 287, in verify_args
    new_elem = dict(new_func_sig.bind(*list(elem)).arguments)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/inspect.py", line 2989, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/Users/omerbelhasin/.pyenv/versions/3.6.7/lib/python3.6/inspect.py", line 2910, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

**Comment by JosepSampe** [comment]
This is not valid input if you want to pass a list. Yo need to enclose it with another list. Check this: https://github.com/pywren/pywren-ibm-cloud/blob/master/docs/functions.md#multiple-function-invocation-using-the-map-and-map_reduce-methods

**Comment by JosepSampe** [comment]
I made pyWren params more 'pythonic' with `args` and `kwargs` in #298. I think this way it is easy to understand how they work.

**Comment by omerb01** [comment]
@JosepSampe can you please elaborate what do you mean by more 'pythonic' ?

**Comment by JosepSampe** [comment]
Any library in python, for example threading and multiprocessing, use `args` in a tuple, and `kwargs` in a dictionary. So i moved everything related to params in pywren to `args` and `kwargs`, which is more natural to understand for python users.
