### ISSUE TITLE
OS error when clean large list of cloud objects

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#305]
when using our new feature `pw.clean(cs=cobjs)` I observe a kernel error when `cobjs` contains too much cloud objects. I assume that we should preallocated the list of cloud objects by a numpy array and it will solve the problem.

Example error:
```
Traceback (most recent call last):
  File "/home/omerbelh/pywren-annotation-pipeline/scripts/run_pipeline.py", line 28, in <module>
    pipeline.clean()
  File "/home/omerbelh/pywren-annotation-pipeline/annotation_pipeline/pipeline.py", line 193, in clean
    self.pywren_executor.clean(cs=cobjects_to_clean)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/executor.py", line 446, in clean
    delete_cloudobject(list(cs), storage_config)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/site-packages/pywren_ibm_cloud/storage/utils.py", line 101, in delete_cloudobject
    os.popen(cmdstr)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/os.py", line 980, in popen
    bufsize=buffering)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/omerbelh/.pyenv/versions/3.6.7/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'
```

**Comment by omerb01** [comment]
@JosepSampe Thanks :) tested and it works
