### ISSUE TITLE
docker runtime - command not found

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#307]
@JosepSampe this happens with the new docker executor. 
When running Docker runtime locally, it fails in the create_runtime

            cmd = 'docker pull {} >/dev/null 2>&1'.format(docker_image_name)
            res = os.system(cmd)
            if res != 0:
                raise Exception('There was an error pulling the runtime')
 

Response code is 32512 which means command not found. The same cmd i can run from cli and it works.

**Comment by JosepSampe** [comment]
@gilv So you have docker installed, and it works if you run `docker pull` directly from console, but it fails if you run it from python?

**Comment by gilv** [comment]
@JosepSampe right...if i copy paste value of "cmd", then i can run from the command line manually. But it fails when i run it with PyWren on command not found

**Comment by JosepSampe** [comment]
Are you using some kind of viertualenv or something like this? Can you try deletening the `>/dev/null 2>&1` from the cmd variable?

**Comment by gilv** [comment]
@JosepSampe i am using  pyenv

**Comment by gilv** [comment]
@JosepSampe This one docker pull cactusone/pywren-3.6-dev:2.0.1 also generate the same error

**Comment by JosepSampe** [comment]
@gilv Try with #308

**Comment by gilv** [comment]
@JosepSampe wow... what was the possible issue that you identified?

**Comment by gilv** [comment]
@JosepSampe there is different error now

2020-05-19 06:23:02,316 [DEBUG] pywren_ibm_cloud.compute.backends.docker.docker: Creating function handler zip in /Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/pywren_docker.zip
2020-05-19 06:23:02,396 [DEBUG] docker.auth: Looking for auth config
2020-05-19 06:23:02,396 [DEBUG] docker.auth: Using credentials store "desktop"
2020-05-19 06:23:02,397 [DEBUG] docker.auth: Looking for auth entry for 'https://index.docker.io/v1/'
Traceback (most recent call last):
  File "/Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/PyWrenTest11.py", line 25, in <module>
    futures = pw.map(my_map_function, iterdata)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/executor.py", line 164, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/invoker.py", line 125, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/compute.py", line 46, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/backends/docker/docker.py", line 157, in create_runtime
    self.docker_client.images.pull(docker_image_name)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/models/images.py", line 445, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/api/image.py", line 396, in pull
    header = auth.get_config_header(self, registry)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/auth.py", line 48, in get_config_header
    client._auth_configs, registry, credstore_env=client.credstore_env
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/auth.py", line 324, in resolve_authconfig
    return authconfig.resolve_authconfig(registry)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/auth.py", line 235, in resolve_authconfig
    cfg = self._resolve_authconfig_credstore(registry, store_name)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
    store = self._get_store_instance(credstore_name)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/auth.py", line 287, in _get_store_instance
    name, environment=self._credstore_env
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/credentials/store.py", line 25, in __init__
    self.program
docker.credentials.errors.InitializationError: docker-credential-desktop not installed or not available in PATH

**Comment by JosepSampe** [comment]
I updated the compute backend to use the docker python sdk instead of raw commands, but seems you still have problems, so I guess at this point it is problem of something related to pyenv or your docker installation.

**Comment by gilv** [comment]
@JosepSampe for you it's work without issues on localhost?

**Comment by JosepSampe** [comment]
@gilv Both versions (docker sdk and raw commands) work without any issue on localhost in my case. I'm using a normal python installation (no pyenv, vierutalenv, etc..)

**Comment by gilv** [comment]
@JosepSampe yeah...it's again something in mac :( Here is explanation what happens https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known/45123074, but i don't get how to resolve it... will avoid running it over mac for now

**Comment by gilv** [comment]
@JosepSampe does PyWren setup environment variable TMPDIR=/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/ ?

In mac it's not /var/folders...it's /private/var/folders..this why it fails on mac.

**Comment by JosepSampe** [comment]
PyWren uses temp folders, they are not hardcoded, it uses `tempfile` library that is supposed to create the temp folder in the correct path independently of the underlying platform (windows, linux, osx)

**Comment by gilv** [comment]
@JosepSampe i updated the tmpdir...and it seems progress but stuck on something else.
Starting point - i don't have any running container, then running the code getting

````
2020-05-19 17:05:48,269 [INFO] pywren_ibm_cloud.config: PyWren v1.5.3-SNAPSHOT
2020-05-19 17:05:48,269 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-05-19 17:05:48,269 [INFO] pywren_ibm_cloud.config: Getting configuration from /Users/gilv/Dev/pywren-ibm-cloud/default_config.yaml
2020-05-19 17:05:48,300 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: docker
2020-05-19 17:05:48,358 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: localhost
2020-05-19 17:05:48,360 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: fc96e7/0
2020-05-19 17:05:48,361 [DEBUG] pywren_ibm_cloud.storage.backends.localhost.localhost: Creating Localhost storage client
2020-05-19 17:05:48,361 [DEBUG] pywren_ibm_cloud.storage.backends.localhost.localhost: Localhost storage client created successfully
2020-05-19 17:05:48,361 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID fc96e7/0 - Total available workers: None
2020-05-19 17:05:48,362 [DEBUG] docker.utils.config: Trying paths: ['/Users/gilv/.docker/config.json', '/Users/gilv/.dockercfg']
2020-05-19 17:05:48,363 [DEBUG] docker.utils.config: Found file at path: /Users/gilv/.docker/config.json
2020-05-19 17:05:48,364 [DEBUG] docker.auth: Found 'auths' section
2020-05-19 17:05:48,364 [DEBUG] docker.auth: Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2020-05-19 17:05:48,364 [INFO] pywren_ibm_cloud.compute.backends.docker.docker: PyWren v1.5.3-SNAPSHOT init for Docker - Host: localhost
2020-05-19 17:05:48,364 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID fc96e7/0 - Creating function invoker
2020-05-19 17:05:48,375 [INFO] pywren_ibm_cloud.invoker: ExecutorID fc96e7/0 | JobID M000 - Selected Runtime: cactusone/pywren-3.6-dev:2.0.1
2020-05-19 17:05:48,375 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in local cache. Retrieving it from storage
2020-05-19 17:05:48,375 [DEBUG] pywren_ibm_cloud.storage.storage: Trying to download runtime metadata from: localhost://gvernikussouth/pywren.runtimes/1.5.3-SNAPSHOT/docker/localhost/pywren_cactusone_pywren-3.6-dev_2.0.1.meta.json
2020-05-19 17:05:48,376 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in storage
2020-05-19 17:05:48,376 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID fc96e7/0 | JobID M000 - Runtime cactusone/pywren-3.6-dev:2.0.1 with NoneMB is not yet installed
2020-05-19 17:05:48,376 [DEBUG] pywren_ibm_cloud.invoker: Creating runtime: cactusone/pywren-3.6-dev:2.0.1, memory: NoneMB
2020-05-19 17:05:48,376 [DEBUG] pywren_ibm_cloud.compute.backends.docker.docker: Creating function handler zip in /Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/pywren_docker.zip
2020-05-19 17:05:48,485 [DEBUG] docker.auth: Looking for auth config
2020-05-19 17:05:48,485 [DEBUG] docker.auth: Looking for auth entry for 'docker.io'
2020-05-19 17:05:48,486 [DEBUG] docker.auth: Found 'https://index.docker.io/v1/'
2020-05-19 17:05:48,486 [DEBUG] docker.auth: No auth config found
Traceback (most recent call last):
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=pywren_cactusone_pywren-3.6-dev_2.0.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/PyWrenTest11.py", line 26, in <module>
    futures = pw.map(my_map_function, iterdata)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/executor.py", line 164, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/invoker.py", line 125, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/compute.py", line 46, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/backends/docker/docker.py", line 166, in create_runtime
    runtime_meta = self._generate_runtime_meta(docker_image_name)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/backends/docker/docker.py", line 119, in _generate_runtime_meta
    self._init_runtime(docker_image_name)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/backends/docker/docker.py", line 100, in _init_runtime
    ports={'8080/tcp': docker_config.PYWREN_SERVER_PORT})
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/models/containers.py", line 803, in run
    detach=detach, **kwargs)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/gilv/.pyenv/versions/3.6.9/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/pywren_cactusone_pywren-3.6-dev_2.0.1" is already in use by container "986a6bebd93f01aa225e3d99a4c5aca342a9bea65aa0139b8e9f3ed515efa698". You have to remove (or rename) that container to be able to reuse that name.")
````

Any ideas?

**Comment by JosepSampe** [comment]
try setting in pywren config file: `compute_backend: docker` and then run: `pywren-ibm-cloud clean`

**Comment by gilv** [comment]
To document the issue for all mac users:
You need to make sure that TMPDIR starts with private not var.
For example
os.environ['TMPDIR']='/private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/' and not 
TMPDIR='/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/'

then go to Docker settings on your mac and choose private/var/ in the File Sharing

**Comment by JosepSampe** [comment]
Reading a similar issue in another place, I found that, `/var/folders/...` is a symlink of /`private/var/folders/...` 

Is it possible that by only settings on your mac: `/private/var/` (in the File Sharing) be enough? Without changing TMPDIR env var?

**Comment by gilv** [comment]
@JosepSampe i tried it ...but it didn't worked

**Comment by JosepSampe** [comment]
Is this what are you experiencing? https://stackoverflow.com/questions/12482702/pythons-os-chdir-and-os-getcwd-mismatch-when-using-tempfile-mkdtemp-on-ma

**Comment by gilv** [comment]
@JosepSampe yes..but somehow i can't reproduce it anymore. i guess it only happens on the 1st time when it need to write into that temp folder, once data is there - no exceptions.
