### ISSUE TITLE
Docker executor need only localhost

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#335]
Docker executor can use remote VM, however the current code fails to use anything than localhost, due to those lines

```
    if 'docker' not in config_data:
        config_data['docker'] = {'host': 'localhost'}

    if config_data['docker']['host'] not in ['127.0.0.1', 'localhost']:
        if 'ssh_user' not in config_data['docker'] or 'ssh_password' not in config_data['docker']:
            raise Exception('You must provide ssh credentials to access to the remote host')

        if config_data['pywren']['storage_backend'] == 'localhost':
            raise Exception('Localhost storage backend is not supported for Docker remote host')
```

**Comment by gilv** [comment]
@JosepSampe you agree with me? :)

**Comment by gilv** [comment]
@JosepSampe may be my mistake...not sure if this is the case..may be my fault

**Comment by JosepSampe** [comment]
@gilv Theoretically the that code is correct. When you use the docker executor, by default it sets the storage backend as "localhost". However, the "localhost" storage backend is not supported if you use a remote VM, so you must specify another publicly accessible storage backend, such as "ibm_cos":
```python
pw = pywren.docker_executor(storage_backend='ibm:cos')
```

**Comment by gilv** [comment]
@JosepSampe am i required to provide runtime for docker executor in case of remote vm? what runtime it suppose to be?
I tried something and it fails..

```
Backend MacOSX is interactive backend. Turning interactive mode on.
2020-08-10 15:11:47,074 [INFO] pywren_ibm_cloud.config: PyWren v1.7.1-SNAPSHOT
2020-08-10 15:11:47,363 [DEBUG] pywren_ibm_cloud.config: Loading configuration
2020-08-10 15:11:48,760 [INFO] pywren_ibm_cloud.config: Getting configuration from /Users/gilv/Dev/pywren-ibm-cloud/default_config.yaml
2020-08-10 15:13:51,474 [DEBUG] pywren_ibm_cloud.config: Loading Compute backend module: docker
2020-08-10 15:13:57,047 [DEBUG] pywren_ibm_cloud.config: Loading Storage backend module: ibm_cos
2020-08-10 15:13:57,236 [DEBUG] pywren_ibm_cloud.executor: FunctionExecutor created with ID: 1e41db/0
2020-08-10 15:13:57,236 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Creating IBM COS client
2020-08-10 15:13:57,236 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Set IBM COS Endpoint to https://s3.us-east.cloud-object-storage.appdomain.cloud
2020-08-10 15:13:57,236 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: Using access_key and secret_key
2020-08-10 15:13:57,329 [DEBUG] pywren_ibm_cloud.storage.backends.ibm_cos.ibm_cos: IBM COS client created successfully
2020-08-10 15:13:57,329 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 1e41db/0 - Total available workers: None
2020-08-10 15:13:57,332 [INFO] pywren_ibm_cloud.compute.backends.docker.docker: PyWren v1.7.1-SNAPSHOT init for Docker - Host: gilv-iris3.sl.cloud9.ibm.com
2020-08-10 15:13:57,332 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 1e41db/0 - Creating function invoker
2020-08-10 15:14:00,571 [INFO] pywren_ibm_cloud.invoker: ExecutorID 1e41db/0 | JobID M000 - Selected Runtime: ibmfunctions/pywren-metabolomics-3.7.5-1.7.0:1.0.0
2020-08-10 15:14:00,572 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in local cache. Retrieving it from storage
2020-08-10 15:14:00,572 [DEBUG] pywren_ibm_cloud.storage.storage: Trying to download runtime metadata from: ibm_cos://gvernikuseast/pywren.runtimes/1.7.1-SNAPSHOT/docker/gilv-iris3.sl.cloud9.ibm.com/pywren_ibmfunctions_pywren-metabolomics-3.7.5-1.7.0_1.0.0.meta.json
2020-08-10 15:14:01,661 [DEBUG] pywren_ibm_cloud.storage.storage: Runtime metadata not found in storage
2020-08-10 15:14:01,661 [DEBUG] pywren_ibm_cloud.invoker: ExecutorID 1e41db/0 | JobID M000 - Runtime ibmfunctions/pywren-metabolomics-3.7.5-1.7.0:1.0.0 with NoneMB is not yet installed
2020-08-10 15:14:01,661 [DEBUG] pywren_ibm_cloud.invoker: Creating runtime: ibmfunctions/pywren-metabolomics-3.7.5-1.7.0:1.0.0, memory: NoneMB
2020-08-10 15:14:01,661 [DEBUG] pywren_ibm_cloud.compute.utils: Creating function handler zip in /Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/pywren_docker.zip
Traceback (most recent call last):
  File "/Users/gilv/.p2/pool/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2316, in <module>
    main()
  File "/Users/gilv/.p2/pool/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2309, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/gilv/.p2/pool/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1642, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Users/gilv/.p2/pool/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1649, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/gilv/.p2/pool/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/PyWrenTest11.py", line 27, in <module>
    futures = pw.map(my_map_function, iterdata)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/executor.py", line 176, in map
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/invoker.py", line 125, in select_runtime
    runtime_meta = compute_handler.create_runtime(runtime_name, runtime_memory, timeout=timeout)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/compute.py", line 63, in create_runtime
    return self.compute_handler.create_runtime(runtime_name, memory, timeout=timeout)
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/backends/docker/docker.py", line 198, in create_runtime
    self._ssh_upload_file(docker_config.FH_ZIP_LOCATION, '/tmp/pywren_docker.zip')
  File "/Users/gilv/Dev/pywren-ibm-cloud/pywren_ibm_cloud/compute/backends/docker/docker.py", line 88, in _ssh_upload_file
    password=self.config['ssh_password'])
  File "/Users/gilv/.pyenv/versions/3.7.5/lib/python3.7/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/Users/gilv/.pyenv/versions/3.7.5/lib/python3.7/site-packages/paramiko/client.py", line 204, in _families_and_addresses
    hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
  File "/Users/gilv/.pyenv/versions/3.7.5/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
