### ISSUE TITLE
Can't read cloud object with ibm_cos

### ISSUE THREAD

**Issue by gilv** [pywren/pywren-ibm-cloud#340]
Tried to run example https://github.com/pywren/pywren-ibm-cloud/blob/master/examples/cloudobject.py
Got 
```
ExecutorID feb9b2/0 | JobID A000 - There was an exception - Activation ID: c7e83e9e5ded40f7a83e9e5dede0f7bf
Traceback (most recent call last):
  File "/action/pywren_ibm_cloud/function/jobrunner.py", line 270, in run
  File "/Users/gilv/Dev/pywren-ibm-cloud/examples/cloudobject.py", line 11, in my_function_put
    co1 = ibm_cos.put_cobject('Cloudobject test 1: {}'.format(text, ))
  File "/usr/local/lib/python3.7/site-packages/ibm_botocore/client.py", line 516, in __getattr__
AttributeError: 'S3' object has no attribute 'put_cobject'
```

@JosepSampe @omerb01 do you know what got broken?

**Comment by gilv** [comment]
fixed in https://github.com/pywren/pywren-ibm-cloud/commit/d494bbd782a1111cf6af21a240578ec33c68869c
