### ISSUE TITLE
NumPy import error

### ISSUE THREAD

**Issue by idoyehe** [pywren/pywren-ibm-cloud#41]
My concurrent limit is 1000 when im trying to execute 1001 actions i get this error:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1689, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/idoye/Documents/PycharmProjects/Industrial_Project_234313/Monte_Carlo/finance_monte_carlo.py", line 93, in <module>
    result_obj = executor.map_reduce_execution(map_function, iterdata, reduce_function)
  File "/Users/idoye/Documents/PycharmProjects/Industrial_Project_234313/ExecuterWrapper/executorWrapper.py", line 52, in map_reduce_execution
    result_object, duration = self._pywren_execution(map_function, iterable_data, reduce_function)
  File "/Users/idoye/Documents/PycharmProjects/Industrial_Project_234313/ExecuterWrapper/executorWrapper.py", line 34, in _pywren_execution
    result_object = pw.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.2-py3.6.egg/pywren_ibm_cloud/wren.py", line 267, in get_result
    verbose=verbose, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.2-py3.6.egg/pywren_ibm_cloud/wren.py", line 308, in _get_result
    throw_except=throw_except, verbose=verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.2-py3.6.egg/pywren_ibm_cloud/future.py", line 278, in result
    reraise(*self._traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "pywren_ibm_cloud/action/jobrunner.py", line 165, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.2-py3.6.egg/pywren_ibm_cloud/executor.py", line 451, in reduce_function_wrapper
    wait(fut_list, executor_id, internal_storage, throw_except)
  File "/action/pywren_ibm_cloud/wait.py", line 69, in wait
  File "/action/pywren_ibm_cloud/wait.py", line 186, in _wait
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 288, in map
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 670, in get
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
  File "/action/pywren_ibm_cloud/wait.py", line 185, in get_result
  File "/action/pywren_ibm_cloud/future.py", line 206, in result
AttributeError: Can't get attribute 'dtype' on <module 'numpy' from  '/usr/local/lib/python3.6/site-packages/numpy/__init__.py'>
```
and it seems because the pywren is trying to import NumPy from wrong folder... in my macbook NumPy installation folder is: 
`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/`

![image](https://user-images.githubusercontent.com/26602913/49326819-8ad9df80-f560-11e8-924b-c888a0360aba.png)

is there any chance to change add it so sys.path?

**Comment by JosepSampe** [comment]
@idoyehe Ensure you imported numpy like: `import numpy as np` and not `from numpy import dtype`. Then use `np.dtype` in the code

**Comment by idoyehe** [comment]
I just tried what you are suggested and fro 1001 it is working but for 2000 I get the same error... and what odd is that this error never happens when I execute actions no more than my limit... and i was NumPy in my code but not dtype explicitly...

**Comment by JosepSampe** [comment]
@idoyehe you got same error with dtype? Exception is produced in your local machine or within reduce function?

**Comment by idoyehe** [comment]
Yes again with dtype... and if I get you right it is happen in my local machine, see the picrute above I debuged it and watch the sys.path veriable..

**Comment by JosepSampe** [comment]
@idoyehe The exception is propagated from function to local machine, so I suspect that it is produced within the function. Can you verify the log of the reduce-method by `bx wsk activation logs <activation_id>`

**Comment by idoyehe** [comment]
```
2018-12-01T10:58:43.226303252Z stdout: [INFO] __main__: Starting IBM Cloud Function execution
2018-12-01T10:58:43.226339508Z stdout: [INFO] wrenhandler: Starting handler
2018-12-01T10:58:43.226345666Z stdout: [INFO] wrenhandler: About to execute 'python pywren_ibm_cloud/action/jobrunner.py /tmp/jobrunner.config.json'
2018-12-01T10:58:43.233036308Z stdout: [INFO] wrenhandler: launched process
2018-12-01T10:58:43.729309058Z stdout: [INFO] jobrunner: Welcome to job runner
2018-12-01T10:58:43.98080243Z  stdout: [INFO] jobrunner: Getting function and modules
2018-12-01T10:58:44.025941718Z stdout: [INFO] jobrunner: Finished getting Function
2018-12-01T10:58:44.025991194Z stdout: [INFO] jobrunner: Writing Function dependencies to local disk
2018-12-01T10:58:44.028193427Z stdout: [INFO] jobrunner: Finished writing Function dependencies
2018-12-01T10:58:44.028210112Z stdout: [INFO] jobrunner: Unpickle Function
2018-12-01T10:58:44.028215158Z stdout: [INFO] jobrunner: Finished Function unpickle
2018-12-01T10:58:44.028219622Z stdout: [INFO] jobrunner: Getting function data
2018-12-01T10:58:44.067765023Z stdout: [INFO] jobrunner: Finished getting Function data
2018-12-01T10:58:44.068037094Z stdout: [INFO] jobrunner: Unpickle Function data
2018-12-01T10:58:44.119960433Z stdout: [INFO] jobrunner: Finished unpickle Function data
2018-12-01T10:58:44.317107303Z stdout: [INFO] jobrunner: Function: Going to execute 'reduce_function_wrapper()'
2018-12-01T10:58:44.317149597Z stdout: ------------------- FUNCTION LOG -------------------
2018-12-01T10:58:44.317524336Z stdout: [INFO] pywren_ibm_cloud.executor: Waiting for results
2018-12-01T10:58:46.908747558Z stdout: [ERROR] jobrunner: There was an exception: Can't get attribute 'dtype' on <module 'numpy' from '/usr/local/lib/python3.5/site-packages/numpy/__init__.py'>
2018-12-01T10:58:46.909109453Z stdout: ----------------------------------------------------
2018-12-01T10:58:47.026339343Z stdout: [DEBUG] pywren_ibm_cloud.storage.backends.cos: PUT Object pywren.jobs/02515663-ab73/5a40e877/00000/output.pickle size 1976 OK
2018-12-01T10:58:47.0453695Z   stdout: [INFO] jobrunner: Jobrunner finished
2018-12-01T10:58:47.18647157Z  stdout: [INFO] wrenhandler: Command execution finished
2018-12-01T10:58:47.332283464Z stdout: [DEBUG] pywren_ibm_cloud.storage.backends.cos: PUT Object pywren.jobs/02515663-ab73/5a40e877/00000/status.json size 765 OK
```
@JosepSampe 

As well I tried to execute my code in watson stdio and I get the same error... and again I want to be clear this error happens ONLY when I try to execute more than my concurrent limit...

**Comment by idoyehe** [comment]
I think I solve it with reinstall the envirment...

**Comment by JosepSampe** [comment]
Not sure what is happening, you should get same behaviour for all activations. Are you using native runtime or custom? In my case I solved the issue by changing the import as I explained before. It may be related to this other issue also with numpy: #31

**Comment by idoyehe** [comment]
update: in my friend account it doesn't happen... we are executring the same code from the same computer

so what could cause that problem?

@JosepSampe @gilv

**Comment by JosepSampe** [comment]
@idoyehe Are you using same region, same runtime?

**Comment by idoyehe** [comment]
yes same runtime and region...
@JosepSampe

**Comment by idoyehe** [comment]
@JosepSampe Thank you, I think it solves the problem
