### ISSUE TITLE
storage_handler usage

### ISSUE THREAD

**Issue by omerb01** [pywren/pywren-ibm-cloud#85]
we need support for using a storage handler that you can get externally from PyWren.

for example:
```python
import pywren_ibm_cloud as pywren

def my_map_function(bucket, key, data_stream, storage_handler):
    data = data_stream.read()
    obj = storage_handler.get_object(bucket, '<BUCKET_NAME>/<KEY>')
    return data, obj

data_stream = '<BUCKET_NAME>/<PREFIX>'
pw = pywren.ibm_cf_executor()
pw.map(my_map_function, data_stream)
print(pw.get_result())
```
this will throw an error instead of export a storage handler:
```
IBM Cloud Functions init for namespace: pywren_dev_us_east and host: https://us-east.functions.cloud.ibm.com
IBM Cloud Functions init for pywren_3.6
IBM Cloud Functions executor created with ID eedcbd2c-c7c3
Traceback (most recent call last):
  File "/Users/omerbelh/IdeaProjects/WORK/python-pywren-example/main.py", line 12, in <module>
    pw.map(my_map_function, data_stream)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.3-py3.6.egg/pywren_ibm_cloud/wren.py", line 143, in map
    exclude_modules=exclude_modules)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.3-py3.6.egg/pywren_ibm_cloud/executor.py", line 216, in multiple_call
    arg_data = wrenutil.verify_args(map_function, data, object_processing=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pywren_ibm_cloud-1.0.3-py3.6.egg/pywren_ibm_cloud/wrenutil.py", line 283, in verify_args
    new_elem = dict(new_func_sig.bind(elem).arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2934, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2849, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'storage_handler'

Process finished with exit code 1
```

**Comment by gilv** [comment]
@omerb01 we call it ibm_cos and storage_handler...
we can add others in the future, like "ibm_db" or something...

**Comment by omerb01** [comment]
@gilv thanks,
there is something wrong with `ibm_cos.get_object()` method,

when you use it like this:
```python
file = ibm_cos.get_object(Bucket='<BUCKET_NAME>', Key='<KEY>')
```
you have to use `file['Body'].read().decode()` to access file's content
I think it would be better if it will just `file`

is there any alternative?

**Comment by gilv** [comment]
@omerb01 i don't know about decode()...but this is standard boto3 library, widely used.
ibm_cos is just an instance of boto3, so we didn't invented anythign new here

**Comment by omerb01** [comment]
@gilv ok thanks
